export default [
  {
    label: 'Southeast Asia',
    label_en_us: 'Southeast Asia',
    label_zh_cn: '东南亚',
    value: 'VN,TH,ID,SG,MY,PH',
    description: ['VN', 'TH', 'ID', 'SG', 'MY', 'PH'],
  },
  {
    label: 'East Asia',
    label_en_us: 'East Asia',
    label_zh_cn: '东亚',
    value: 'TW',
    description: ['TW'],
  },
  {
    label: 'Middle East',
    label_en_us: 'Middle East',
    label_zh_cn: '中东',
    value: 'SA',
    description: ['SA'],
  },
  {
    label: 'Russia',
    label_en_us: 'Russia',
    label_zh_cn: '俄罗斯',
    value: 'RU',
    description: ['RU'],
  },
  {
    label: 'Latin America',
    label_en_us: 'Latin America',
    label_zh_cn: '拉丁美洲',
    value: 'MX,AR',
    description: ['MX', 'AR'],
  },
  {
    label: 'South Korea',
    label_en_us: 'South Korea',
    label_zh_cn: '南韩',
    value: 'KR',
    description: ['KR'],
  },
  {
    label: 'Japan',
    label_en_us: 'Japan',
    label_zh_cn: '日本',
    value: 'JP',
    description: ['JP'],
  },
  {
    label: 'South Asia',
    label_en_us: 'South Asia',
    label_zh_cn: '南亚',
    value: 'IN',
    description: ['IN'],
  },
  {
    label: 'Europe',
    label_en_us: 'Europe',
    label_zh_cn: '欧洲',
    value: 'ES,IT,DE,GB,FR,AU',
    description: ['ES', 'IT', 'DE', 'GB', 'FR', 'AU'],
  },
  {
    label: 'North America',
    label_en_us: 'North America',
    label_zh_cn: '北美洲',
    value: 'CA,US',
    description: ['CA', 'US'],
  },
  {
    label: 'China',
    label_en_us: 'China',
    label_zh_cn: '中国',
    value: 'CN',
    description: ['CN'],
  },
];
