export default {
  label: '北美洲',
  sort: 30,
  list: [
    {
      icon: 'area-ai',
      addr: 'AI',
      name: '安圭拉',
      label: 'Anguilla',
      addrlower: 'ai',
    },
    {
      icon: 'area-ag',
      addr: 'AG',
      name: '安提瓜和巴布达',
      label: 'Antigua',
      addrlower: 'ag',
    },
    {
      icon: 'area-bb',
      addr: 'BB',
      name: '巴巴多斯',
      label: 'Barbados',
      addrlower: 'bb',
    },
    {
      icon: 'area-bs',
      addr: 'BS',
      name: '巴哈马',
      label: 'Bahamas',
      addrlower: 'bs',
    },
    {
      icon: 'area-pa',
      addr: 'PA',
      name: '巴拿马',
      label: 'Panama',
      addrlower: 'pa',
    },
    {
      icon: 'area-bm',
      addr: 'BM',
      name: '百慕大',
      label: 'Bermuda',
      addrlower: 'bm',
    },
    {
      icon: 'area-bz',
      addr: 'BZ',
      name: '伯利兹',
      label: 'Belize',
      addrlower: 'bz',
    },
    {
      icon: 'area-do',
      addr: 'DO',
      name: '多米尼加',
      label: 'Dominican',
      addrlower: 'do',
    },
    {
      icon: 'area-dm',
      addr: 'DM',
      name: '多米尼克',
      label: 'Dominica',
      addrlower: 'dm',
    },
    {
      icon: 'area-cr',
      addr: 'CR',
      name: '哥斯达黎加',
      label: 'Costa',
      addrlower: 'cr',
    },
    {
      icon: 'area-gd',
      addr: 'GD',
      name: '格林纳达',
      label: 'Grenada',
      addrlower: 'gd',
    },
    {
      icon: 'area-hn',
      addr: 'HN',
      name: '洪都拉斯',
      label: 'Honduras',
      addrlower: 'hn',
    },
    {
      icon: 'area-ca',
      addr: 'CA',
      name: '加拿大',
      label: 'Canada',
      addrlower: 'ca',
    },
    {
      icon: 'area-ky',
      addr: 'KY',
      name: '开曼群岛',
      label: 'Cayman',
      addrlower: 'ky',
    },
    {
      icon: 'area-ms',
      addr: 'MS',
      name: '蒙特塞拉特',
      label: 'Montserrat',
      addrlower: 'ms',
    },
    {
      icon: 'area-mx',
      addr: 'MX',
      name: '墨西哥',
      label: 'Mexico',
      addrlower: 'mx',
    },
    {
      icon: 'area-ni',
      addr: 'NI',
      name: '尼加拉瓜',
      label: 'Nicaragua',
      addrlower: 'ni',
    },
    {
      icon: 'area-sv',
      addr: 'SV',
      name: '萨尔瓦多',
      label: 'El',
      addrlower: 'sv',
    },
    {
      icon: 'area-kn',
      addr: 'KN',
      name: '圣基茨和尼维斯',
      label: 'Saint',
      addrlower: 'kn',
    },
    {
      icon: 'area-lc',
      addr: 'LC',
      name: '圣卢西亚',
      label: 'Saint',
      addrlower: 'lc',
    },
    {
      icon: 'area-vc',
      addr: 'VC',
      name: '圣文森特和格林纳丁斯',
      label: 'Saint',
      addrlower: 'vc',
    },
    {
      icon: 'area-tc',
      addr: 'TC',
      name: '特克斯和凯科斯群岛',
      label: 'Turks',
      addrlower: 'tc',
    },
    {
      icon: 'area-tt',
      addr: 'TT',
      name: '特立尼达和多巴哥',
      label: 'Trinidad',
      addrlower: 'tt',
    },
    {
      icon: 'area-gt',
      addr: 'GT',
      name: '危地马拉',
      label: 'Guatemala',
      addrlower: 'gt',
    },
    {
      icon: 'area-jm',
      addr: 'JM',
      name: '牙买加',
      label: 'Jamaica',
      addrlower: 'jm',
    },
    {
      icon: 'area-vg',
      addr: 'VG',
      name: '英属维尔京群岛',
      label: 'Virgin',
      addrlower: 'vg',
    },
  ],
};
