export default {
  label: '非洲',
  sort: 70,
  list: [
    {
      icon: 'area-dz',
      addr: 'DZ',
      name: '阿尔及利亚',
      label: 'Algeria',
      addrlower: 'dz',
    },
    {
      icon: 'area-eg',
      addr: 'EG',
      name: '埃及',
      label: 'Egypt',
      addrlower: 'eg',
    },
    {
      icon: 'area-ao',
      addr: 'AO',
      name: '安哥拉',
      label: 'Angola',
      addrlower: 'ao',
    },
    {
      icon: 'area-bj',
      addr: 'BJ',
      name: '贝宁',
      label: 'Benin',
      addrlower: 'bj',
    },
    {
      icon: 'area-bw',
      addr: 'BW',
      name: '博茨瓦纳',
      label: 'Botswana',
      addrlower: 'bw',
    },
    {
      icon: 'area-bf',
      addr: 'BF',
      name: '布基纳法索',
      label: 'Burkina',
      addrlower: 'bf',
    },
    {
      icon: 'area-cv',
      addr: 'CV',
      name: '佛得角',
      label: 'Cabo',
      addrlower: 'cv',
    },
    {
      icon: 'area-gm',
      addr: 'GM',
      name: '冈比亚',
      label: 'Gambia',
      addrlower: 'gm',
    },
    {
      icon: 'area-cg',
      addr: 'CG',
      name: '刚果（布）',
      label: 'Congo',
      addrlower: 'cg',
    },
    {
      icon: 'area-gw',
      addr: 'GW',
      name: '几内亚比绍',
      label: 'Guinea-Bissau',
      addrlower: 'gw',
    },
    {
      icon: 'area-gh',
      addr: 'GH',
      name: '加纳',
      label: 'Ghana',
      addrlower: 'gh',
    },
    {
      icon: 'area-zw',
      addr: 'ZW',
      name: '津巴布韦',
      label: 'Zimbabwe',
      addrlower: 'zw',
    },
    {
      icon: 'area-ke',
      addr: 'KE',
      name: '肯尼亚',
      label: 'Kenya',
      addrlower: 'ke',
    },
    {
      icon: 'area-lr',
      addr: 'LR',
      name: '利比里亚',
      label: 'Liberia',
      addrlower: 'lr',
    },
    {
      icon: 'area-mg',
      addr: 'MG',
      name: '马达加斯加',
      label: 'Madagascar',
      addrlower: 'mg',
    },
    {
      icon: 'area-mw',
      addr: 'MW',
      name: '马拉维',
      label: 'Malawi',
      addrlower: 'mw',
    },
    {
      icon: 'area-ml',
      addr: 'ML',
      name: '马里',
      label: 'Mali',
      addrlower: 'ml',
    },
    {
      icon: 'area-mu',
      addr: 'MU',
      name: '毛里求斯',
      label: 'Mauritius',
      addrlower: 'mu',
    },
    {
      icon: 'area-mr',
      addr: 'MR',
      name: '毛里塔尼亚',
      label: 'Mauritania',
      addrlower: 'mr',
    },
    {
      icon: 'area-mz',
      addr: 'MZ',
      name: '莫桑比克',
      label: 'Mozambique',
      addrlower: 'mz',
    },
    {
      icon: 'area-na',
      addr: 'NA',
      name: '纳米比亚',
      label: 'Namibia',
      addrlower: 'na',
    },
    {
      icon: 'area-za',
      addr: 'ZA',
      name: '南非',
      label: 'South',
      addrlower: 'za',
    },
    {
      icon: 'area-ne',
      addr: 'NE',
      name: '尼日尔',
      label: 'Niger',
      addrlower: 'ne',
    },
    {
      icon: 'area-ng',
      addr: 'NG',
      name: '尼日利亚',
      label: 'Nigeria',
      addrlower: 'ng',
    },
    {
      icon: 'area-sn',
      addr: 'SN',
      name: '塞内加尔',
      label: 'Senegal',
      addrlower: 'sn',
    },
    {
      icon: 'area-cy',
      addr: 'CY',
      name: '塞浦路斯',
      label: 'Cyprus',
      addrlower: 'cy',
    },
    {
      icon: 'area-sc',
      addr: 'SC',
      name: '塞舌尔',
      label: 'Seychelles',
      addrlower: 'sc',
    },
    {
      icon: 'area-st',
      addr: 'ST',
      name: '圣多美和普林西比',
      label: 'Sao',
      addrlower: 'st',
    },
    {
      icon: 'area-sz',
      addr: 'SZ',
      name: '斯威士兰',
      label: 'Eswatini',
      addrlower: 'sz',
    },
    {
      icon: 'area-tz',
      addr: 'TZ',
      name: '坦桑尼亚',
      label: 'Tanzania,',
      addrlower: 'tz',
    },
    {
      icon: 'area-tn',
      addr: 'TN',
      name: '突尼斯',
      label: 'Tunisia',
      addrlower: 'tn',
    },
    {
      icon: 'area-ug',
      addr: 'UG',
      name: '乌干达',
      label: 'Uganda',
      addrlower: 'ug',
    },
    {
      icon: 'area-td',
      addr: 'TD',
      name: '乍得',
      label: 'Chad',
      addrlower: 'td',
    },
  ],
};
