export default {
  label: '南美洲',
  sort: 40,
  list: [
    {
      icon: 'area-ar',
      addr: 'AR',
      name: '阿根廷',
      label: 'Argentina',
      addrlower: 'ar',
    },
    {
      icon: 'area-py',
      addr: 'PY',
      name: '巴拉圭',
      label: 'Paraguay',
      addrlower: 'py',
    },
    {
      icon: 'area-br',
      addr: 'BR',
      name: '巴西',
      label: 'Brazil',
      addrlower: 'br',
    },
    {
      icon: 'area-bo',
      addr: 'BO',
      name: '玻利维亚',
      label: 'Bolivia,',
      addrlower: 'bo',
    },
    {
      icon: 'area-ec',
      addr: 'EC',
      name: '厄瓜多尔',
      label: 'Ecuador',
      addrlower: 'ec',
    },
    {
      icon: 'area-co',
      addr: 'CO',
      name: '哥伦比亚',
      label: 'Colombia',
      addrlower: 'co',
    },
    {
      icon: 'area-gy',
      addr: 'GY',
      name: '圭亚那',
      label: 'Guyana',
      addrlower: 'gy',
    },
    {
      icon: 'area-pe',
      addr: 'PE',
      name: '秘鲁',
      label: 'Peru',
      addrlower: 'pe',
    },
    {
      icon: 'area-sr',
      addr: 'SR',
      name: '苏里南',
      label: 'Suriname',
      addrlower: 'sr',
    },
    {
      icon: 'area-ve',
      addr: 'VE',
      name: '委内瑞拉',
      label: 'Venezuela,',
      addrlower: 've',
    },
    {
      icon: 'area-uy',
      addr: 'UY',
      name: '乌拉圭',
      label: 'Uruguay',
      addrlower: 'uy',
    },
    {
      icon: 'area-cl',
      addr: 'CL',
      name: '智利',
      label: 'Chile',
      addrlower: 'cl',
    },
  ],
};
