export default {
  label: '欧洲',
  sort: 20,
  list: [
    {
      icon: 'area-al',
      addr: 'AL',
      name: '阿尔巴尼亚',
      label: 'Albania',
      addrlower: 'al',
    },
    {
      icon: 'area-ie',
      addr: 'IE',
      name: '爱尔兰',
      label: 'Ireland',
      addrlower: 'ie',
    },
    {
      icon: 'area-ee',
      addr: 'EE',
      name: '爱沙尼亚',
      label: 'Estonia',
      addrlower: 'ee',
    },
    {
      icon: 'area-at',
      addr: 'AT',
      name: '奥地利',
      label: 'Austria',
      addrlower: 'at',
    },
    {
      icon: 'area-by',
      addr: 'BY',
      name: '白俄罗斯',
      label: 'Belarus',
      addrlower: 'by',
    },
    {
      icon: 'area-bg',
      addr: 'BG',
      name: '保加利亚',
      label: 'Bulgaria',
      addrlower: 'bg',
    },
    {
      icon: 'area-mk',
      addr: 'MK',
      name: '北马其顿',
      label: 'North',
      addrlower: 'mk',
    },
    {
      icon: 'area-be',
      addr: 'BE',
      name: '比利时',
      label: 'Belgium',
      addrlower: 'be',
    },
    {
      icon: 'area-is',
      addr: 'IS',
      name: '冰岛',
      label: 'Iceland',
      addrlower: 'is',
    },
    {
      icon: 'area-pl',
      addr: 'PL',
      name: '波兰',
      label: 'Poland',
      addrlower: 'pl',
    },
    {
      icon: 'area-dk',
      addr: 'DK',
      name: '丹麦',
      label: 'Denmark',
      addrlower: 'dk',
    },
    {
      icon: 'area-de',
      addr: 'DE',
      name: '德国',
      label: 'Germany',
      addrlower: 'de',
    },
    {
      icon: 'area-ru',
      addr: 'RU',
      name: '俄罗斯',
      label: 'Russian',
      addrlower: 'ru',
    },
    {
      icon: 'area-fr',
      addr: 'FR',
      name: '法国',
      label: 'France',
      addrlower: 'fr',
    },
    {
      icon: 'area-fi',
      addr: 'FI',
      name: '芬兰',
      label: 'Finland',
      addrlower: 'fi',
    },
    {
      icon: 'area-nl',
      addr: 'NL',
      name: '荷兰',
      label: 'Netherlands',
      addrlower: 'nl',
    },
    {
      icon: 'area-cz',
      addr: 'CZ',
      name: '捷克',
      label: 'Czech',
      addrlower: 'cz',
    },
    {
      icon: 'area-hr',
      addr: 'HR',
      name: '克罗地亚',
      label: 'Croatia',
      addrlower: 'hr',
    },
    {
      icon: 'area-lv',
      addr: 'LV',
      name: '拉脱维亚',
      label: 'Latvia',
      addrlower: 'lv',
    },
    {
      icon: 'area-lt',
      addr: 'LT',
      name: '立陶宛',
      label: 'Lithuania',
      addrlower: 'lt',
    },
    {
      icon: 'area-lu',
      addr: 'LU',
      name: '卢森堡',
      label: 'Luxembourg',
      addrlower: 'lu',
    },
    {
      icon: 'area-ro',
      addr: 'RO',
      name: '罗马尼亚',
      label: 'Romania',
      addrlower: 'ro',
    },
    {
      icon: 'area-mt',
      addr: 'MT',
      name: '马耳他',
      label: 'Malta',
      addrlower: 'mt',
    },
    {
      icon: 'area-md',
      addr: 'MD',
      name: '摩尔多瓦',
      label: 'Moldova,',
      addrlower: 'md',
    },
    {
      icon: 'area-no',
      addr: 'NO',
      name: '挪威',
      label: 'Norway',
      addrlower: 'no',
    },
    {
      icon: 'area-pt',
      addr: 'PT',
      name: '葡萄牙',
      label: 'Portugal',
      addrlower: 'pt',
    },
    {
      icon: 'area-se',
      addr: 'SE',
      name: '瑞典',
      label: 'Sweden',
      addrlower: 'se',
    },
    {
      icon: 'area-ch',
      addr: 'CH',
      name: '瑞士',
      label: 'Switzerland',
      addrlower: 'ch',
    },
    {
      icon: 'area-sl',
      addr: 'SL',
      name: '塞拉利昂',
      label: 'Sierra',
      addrlower: 'sl',
    },
    {
      icon: 'area-sk',
      addr: 'SK',
      name: '斯洛伐克',
      label: 'Slovakia',
      addrlower: 'sk',
    },
    {
      icon: 'area-si',
      addr: 'SI',
      name: '斯洛文尼亚',
      label: 'Slovenia',
      addrlower: 'si',
    },
    {
      icon: 'area-ua',
      addr: 'UA',
      name: '乌克兰',
      label: 'Ukraine',
      addrlower: 'ua',
    },
    {
      icon: 'area-es',
      addr: 'ES',
      name: '西班牙',
      label: 'Spain',
      addrlower: 'es',
    },
    {
      icon: 'area-gr',
      addr: 'GR',
      name: '希腊',
      label: 'Greece',
      addrlower: 'gr',
    },
    {
      icon: 'area-hu',
      addr: 'HU',
      name: '匈牙利',
      label: 'Hungary',
      addrlower: 'hu',
    },
    {
      icon: 'area-it',
      addr: 'IT',
      name: '意大利',
      label: 'Italia',
      addrlower: 'it',
    },
    { icon: 'area-gb', addr: 'GB', name: '英国', label: 'UK', addrlower: 'gb' },
  ],
};
