export default {
  label: '亚洲',
  sort: 10,
  list: [
    {
      icon: 'area-ae',
      addr: 'AE',
      name: '阿联酋',
      label: 'United',
      addrlower: 'ae',
    },
    {
      icon: 'area-om',
      addr: 'OM',
      name: '阿曼',
      label: 'Oman',
      addrlower: 'om',
    },
    {
      icon: 'area-az',
      addr: 'AZ',
      name: '阿塞拜疆',
      label: 'Azerbaijan',
      addrlower: 'az',
    },
    {
      icon: 'area-pk',
      addr: 'PK',
      name: '巴基斯坦',
      label: 'Pakistan',
      addrlower: 'pk',
    },
    {
      icon: 'area-bh',
      addr: 'BH',
      name: '巴林',
      label: 'Bahrain',
      addrlower: 'bh',
    },
    {
      icon: 'area-bt',
      addr: 'BT',
      name: '不丹',
      label: 'Bhutan',
      addrlower: 'bt',
    },
    {
      icon: 'area-ph',
      addr: 'PH',
      name: '菲律宾',
      label: 'Philippines',
      addrlower: 'ph',
    },
    {
      icon: 'area-kz',
      addr: 'KZ',
      name: '哈萨克斯坦',
      label: 'Kazakhstan',
      addrlower: 'kz',
    },
    {
      icon: 'area-kg',
      addr: 'KG',
      name: '吉尔吉斯斯坦',
      label: 'Kyrgyzstan',
      addrlower: 'kg',
    },
    {
      icon: 'area-kh',
      addr: 'KH',
      name: '柬埔寨',
      label: 'Cambodia',
      addrlower: 'kh',
    },
    {
      icon: 'area-qa',
      addr: 'QA',
      name: '卡塔尔',
      label: 'Qatar',
      addrlower: 'qa',
    },
    {
      icon: 'area-kw',
      addr: 'KW',
      name: '科威特',
      label: 'Kuwait',
      addrlower: 'kw',
    },
    {
      icon: 'area-la',
      addr: 'LA',
      name: '老挝',
      label: 'Lao',
      addrlower: 'la',
    },
    {
      icon: 'area-lb',
      addr: 'LB',
      name: '黎巴嫩',
      label: 'Lebanon',
      addrlower: 'lb',
    },
    {
      icon: 'area-my',
      addr: 'MY',
      name: '马来西亚',
      label: 'Malaysia',
      addrlower: 'my',
    },
    {
      icon: 'area-mn',
      addr: 'MN',
      name: '蒙古国',
      label: 'Mongolia',
      addrlower: 'mn',
    },
    {
      icon: 'area-np',
      addr: 'NP',
      name: '尼泊尔',
      label: 'Nepal',
      addrlower: 'np',
    },
    {
      icon: 'area-sa',
      addr: 'SA',
      name: '沙特阿拉伯',
      label: 'Saudi',
      addrlower: 'sa',
    },
    {
      icon: 'area-lk',
      addr: 'LK',
      name: '斯里兰卡',
      label: 'Sri',
      addrlower: 'lk',
    },
    {
      icon: 'area-tj',
      addr: 'TJ',
      name: '塔吉克斯坦',
      label: 'Tajikistan',
      addrlower: 'tj',
    },
    {
      icon: 'area-th',
      addr: 'TH',
      name: '泰国',
      label: 'Thailand',
      addrlower: 'th',
    },
    {
      icon: 'area-tr',
      addr: 'TR',
      name: '土耳其',
      label: 'Turkey',
      addrlower: 'tr',
    },
    {
      icon: 'area-tm',
      addr: 'TM',
      name: '土库曼斯坦',
      label: 'Turkmenistan',
      addrlower: 'tm',
    },
    {
      icon: 'area-bn',
      addr: 'BN',
      name: '文莱',
      label: 'Brunei',
      addrlower: 'bn',
    },
    {
      icon: 'area-uz',
      addr: 'UZ',
      name: '乌兹别克斯坦',
      label: 'Uzbekistan',
      addrlower: 'uz',
    },
    {
      icon: 'area-sg',
      addr: 'SG',
      name: '新加坡',
      label: 'Singapore',
      addrlower: 'sg',
    },
    {
      icon: 'area-am',
      addr: 'AM',
      name: '亚美尼亚',
      label: 'Armenia',
      addrlower: 'am',
    },
    {
      icon: 'area-ye',
      addr: 'YE',
      name: '也门',
      label: 'Yemen',
      addrlower: 'ye',
    },
    {
      icon: 'area-il',
      addr: 'IL',
      name: '以色列',
      label: 'Israel',
      addrlower: 'il',
    },
    {
      icon: 'area-in',
      addr: 'IN',
      name: '印度',
      label: 'India',
      addrlower: 'in',
    },
    {
      icon: 'area-id',
      addr: 'ID',
      name: '印尼',
      label: 'Indonesia',
      addrlower: 'id',
    },
    {
      icon: 'area-jo',
      addr: 'JO',
      name: '约旦',
      label: 'Jordan',
      addrlower: 'jo',
    },
    {
      icon: 'area-vn',
      addr: 'VN',
      name: '越南',
      label: 'Vietnam',
      addrlower: 'vn',
    },
    {
      icon: 'area-mo',
      addr: 'MO',
      name: '中国澳门',
      label: 'Macao',
      addrlower: 'mo',
    },
  ],
};
