export default [
  {
    label: '中国',
    label_en_us: 'China',
    label_zh_cn: '中国',
    value: 'CN',
    value_lower: 'cn',
  },
  {
    label: '美国',
    label_en_us: 'U.S.A',
    label_zh_cn: '美国',
    value: 'US',
    value_lower: 'us',
  },
  {
    label: '香港',
    label_en_us: 'Hong Kong',
    label_zh_cn: '香港',
    value: 'HK',
    value_lower: 'hk',
  },
  {
    label: '中国台湾省',
    label_en_us: 'Taiwan, China Province, China',
    label_zh_cn: '中国台湾省',
    value: 'TW',
    value_lower: 'tw',
  },
  {
    label: '日本',
    label_en_us: 'Japan',
    label_zh_cn: '日本',
    value: 'JP',
    value_lower: 'jp',
  },
  {
    label: '韩国',
    label_en_us: 'Korea',
    label_zh_cn: '韩国',
    value: 'KR',
    value_lower: 'kr',
  },
  {
    label: '土耳其',
    label_en_us: 'Türkiye',
    label_zh_cn: '土耳其',
    value: 'TR',
    value_lower: 'tr',
  },
  {
    label: '英国',
    label_en_us: 'Britain',
    label_zh_cn: '英国',
    value: 'GB',
    value_lower: 'gb',
  },
  {
    label: '澳门',
    label_en_us: 'Macao',
    label_zh_cn: '澳门',
    value: 'MO',
    value_lower: 'mo',
  },
  {
    label: '巴基斯坦',
    label_en_us: 'Pakistan',
    label_zh_cn: '巴基斯坦',
    value: 'PK',
    value_lower: 'pk',
  },
  {
    label: '不丹',
    label_en_us: 'Bhutan',
    label_zh_cn: '不丹',
    value: 'BT',
    value_lower: 'bt',
  },
  {
    label: '菲律宾',
    label_en_us: 'The Philippines',
    label_zh_cn: '菲律宾',
    value: 'PH',
    value_lower: 'ph',
  },
  {
    label: '哈萨克斯坦',
    label_en_us: 'Kazakhstan',
    label_zh_cn: '哈萨克斯坦',
    value: 'KZ',
    value_lower: 'kz',
  },
  {
    label: '吉尔吉斯斯坦',
    label_en_us: 'Kyrgyzstan',
    label_zh_cn: '吉尔吉斯斯坦',
    value: 'KG',
    value_lower: 'kg',
  },
  {
    label: '柬埔寨',
    label_en_us: 'Cambodia',
    label_zh_cn: '柬埔寨',
    value: 'KH',
    value_lower: 'kh',
  },
  {
    label: '老挝人民民主共和国',
    label_en_us: "Lao People's Democratic Republic",
    label_zh_cn: '老挝人民民主共和国',
    value: 'LA',
    value_lower: 'la',
  },
  {
    label: '马来西亚',
    label_en_us: 'Malaysia',
    label_zh_cn: '马来西亚',
    value: 'MY',
    value_lower: 'my',
  },
  {
    label: '蒙古',
    label_en_us: 'Mongolia',
    label_zh_cn: '蒙古',
    value: 'MN',
    value_lower: 'mn',
  },
  {
    label: '尼泊尔',
    label_en_us: 'Nepal',
    label_zh_cn: '尼泊尔',
    value: 'NP',
    value_lower: 'np',
  },
  {
    label: '斯里兰卡',
    label_en_us: 'Sri Lanka',
    label_zh_cn: '斯里兰卡',
    value: 'LK',
    value_lower: 'lk',
  },
  {
    label: '塔吉克斯坦',
    label_en_us: 'Tajikistan',
    label_zh_cn: '塔吉克斯坦',
    value: 'TJ',
    value_lower: 'tj',
  },
  {
    label: '泰国',
    label_en_us: 'Thailand',
    label_zh_cn: '泰国',
    value: 'TH',
    value_lower: 'th',
  },
  {
    label: '土库曼斯坦',
    label_en_us: 'Turkmenistan',
    label_zh_cn: '土库曼斯坦',
    value: 'TM',
    value_lower: 'tm',
  },
  {
    label: '文莱',
    label_en_us: 'Brunei',
    label_zh_cn: '文莱',
    value: 'BN',
    value_lower: 'bn',
  },
  {
    label: '乌兹别克斯坦',
    label_en_us: 'Uzbekistan',
    label_zh_cn: '乌兹别克斯坦',
    value: 'UZ',
    value_lower: 'uz',
  },
  {
    label: '新加坡',
    label_en_us: 'Singapore',
    label_zh_cn: '新加坡',
    value: 'SG',
    value_lower: 'sg',
  },
  {
    label: '印尼',
    label_en_us: 'Indonesia',
    label_zh_cn: '印尼',
    value: 'ID',
    value_lower: 'id',
  },
  {
    label: '越南',
    label_en_us: 'Vietnam',
    label_zh_cn: '越南',
    value: 'VN',
    value_lower: 'vn',
  },
  {
    label: '阿联酋',
    label_en_us: 'The United Arab Emirates',
    label_zh_cn: '阿联酋',
    value: 'AE',
    value_lower: 'ae',
  },
  {
    label: '阿曼',
    label_en_us: 'Oman',
    label_zh_cn: '阿曼',
    value: 'OM',
    value_lower: 'om',
  },
  {
    label: '阿塞拜疆',
    label_en_us: 'Azerbaijan',
    label_zh_cn: '阿塞拜疆',
    value: 'AZ',
    value_lower: 'az',
  },
  {
    label: '巴林',
    label_en_us: 'Bahrain',
    label_zh_cn: '巴林',
    value: 'BH',
    value_lower: 'bh',
  },
  {
    label: '卡塔尔',
    label_en_us: 'Qatar',
    label_zh_cn: '卡塔尔',
    value: 'QA',
    value_lower: 'qa',
  },
  {
    label: '科威特',
    label_en_us: 'Kuwait',
    label_zh_cn: '科威特',
    value: 'KW',
    value_lower: 'kw',
  },
  {
    label: '黎巴嫩',
    label_en_us: 'Lebanon',
    label_zh_cn: '黎巴嫩',
    value: 'LB',
    value_lower: 'lb',
  },
  {
    label: '沙特阿拉伯',
    label_en_us: 'Saudi Arabia',
    label_zh_cn: '沙特阿拉伯',
    value: 'SA',
    value_lower: 'sa',
  },
  {
    label: '亚美尼亚',
    label_en_us: 'Armenia',
    label_zh_cn: '亚美尼亚',
    value: 'AM',
    value_lower: 'am',
  },
  {
    label: '也门',
    label_en_us: 'Yemen',
    label_zh_cn: '也门',
    value: 'YE',
    value_lower: 'ye',
  },
  {
    label: '以色列',
    label_en_us: 'Israel',
    label_zh_cn: '以色列',
    value: 'IL',
    value_lower: 'il',
  },
  {
    label: '印度',
    label_en_us: 'India',
    label_zh_cn: '印度',
    value: 'IN',
    value_lower: 'in',
  },
  {
    label: '约旦',
    label_en_us: 'Jordan',
    label_zh_cn: '约旦',
    value: 'JO',
    value_lower: 'jo',
  },
  {
    label: '加拿大',
    label_en_us: 'Canada',
    label_zh_cn: '加拿大',
    value: 'CA',
    value_lower: 'ca',
  },
  {
    label: '安圭拉',
    label_en_us: 'Anguilla ',
    label_zh_cn: '安圭拉',
    value: 'AI',
    value_lower: 'ai',
  },
  {
    label: '安提瓜和巴布达',
    label_en_us: 'Antigua and Barbuda ',
    label_zh_cn: '安提瓜和巴布达',
    value: 'AG',
    value_lower: 'ag',
  },
  {
    label: '巴巴多斯',
    label_en_us: 'Barbados',
    label_zh_cn: '巴巴多斯',
    value: 'BB',
    value_lower: 'bb',
  },
  {
    label: '巴哈马',
    label_en_us: 'Bahamas',
    label_zh_cn: '巴哈马',
    value: 'BS',
    value_lower: 'bs',
  },
  {
    label: '巴拿马',
    label_en_us: 'Panama',
    label_zh_cn: '巴拿马',
    value: 'PA',
    value_lower: 'pa',
  },
  {
    label: '百慕大',
    label_en_us: 'Bermuda',
    label_zh_cn: '百慕大',
    value: 'BM',
    value_lower: 'bm',
  },
  {
    label: '伯利兹',
    label_en_us: 'Belize ',
    label_zh_cn: '伯利兹',
    value: 'BZ',
    value_lower: 'bz',
  },
  {
    label: '多米尼加共和国',
    label_en_us: 'Dominican Republic',
    label_zh_cn: '多米尼加共和国',
    value: 'DO',
    value_lower: 'do',
  },
  {
    label: '多米尼克',
    label_en_us: 'Dominica',
    label_zh_cn: '多米尼克',
    value: 'DM',
    value_lower: 'dm',
  },
  {
    label: '哥斯达黎加',
    label_en_us: 'Costa Rica',
    label_zh_cn: '哥斯达黎加',
    value: 'CR',
    value_lower: 'cr',
  },
  {
    label: '格林纳达',
    label_en_us: 'Grenada',
    label_zh_cn: '格林纳达',
    value: 'GD',
    value_lower: 'gd',
  },
  {
    label: '洪都拉斯',
    label_en_us: 'Honduras',
    label_zh_cn: '洪都拉斯',
    value: 'HN',
    value_lower: 'hn',
  },
  {
    label: '开曼群岛',
    label_en_us: 'Cayman Islands',
    label_zh_cn: '开曼群岛',
    value: 'KY',
    value_lower: 'ky',
  },
  {
    label: '蒙特塞拉特岛',
    label_en_us: 'Montserrat',
    label_zh_cn: '蒙特塞拉特岛',
    value: 'MS',
    value_lower: 'ms',
  },
  {
    label: '墨西哥',
    label_en_us: 'Mexico',
    label_zh_cn: '墨西哥',
    value: 'MX',
    value_lower: 'mx',
  },
  {
    label: '尼加拉瓜',
    label_en_us: 'Nicaragua',
    label_zh_cn: '尼加拉瓜',
    value: 'NI',
    value_lower: 'ni',
  },
  {
    label: '萨尔瓦多',
    label_en_us: 'El Salvador',
    label_zh_cn: '萨尔瓦多',
    value: 'SV',
    value_lower: 'sv',
  },
  {
    label: '圣基茨岛和尼维斯',
    label_en_us: 'St Kitts and Nevis ',
    label_zh_cn: '圣基茨岛和尼维斯',
    value: 'KN',
    value_lower: 'kn',
  },
  {
    label: '圣卢西亚',
    label_en_us: 'Saint Lucia ',
    label_zh_cn: '圣卢西亚',
    value: 'LC',
    value_lower: 'lc',
  },
  {
    label: '圣文森特和格林纳丁斯',
    label_en_us: 'Saint Vincent and the Grenadines',
    label_zh_cn: '圣文森特和格林纳丁斯',
    value: 'VC',
    value_lower: 'vc',
  },
  {
    label: '特克斯和凯科斯群岛',
    label_en_us: 'Turks and Caicos Islands ',
    label_zh_cn: '特克斯和凯科斯群岛',
    value: 'TC',
    value_lower: 'tc',
  },
  {
    label: '特立尼达和多巴哥',
    label_en_us: 'Trinidad and Tobago ',
    label_zh_cn: '特立尼达和多巴哥',
    value: 'TT',
    value_lower: 'tt',
  },
  {
    label: '危地马拉',
    label_en_us: 'Guatemala',
    label_zh_cn: '危地马拉',
    value: 'GT',
    value_lower: 'gt',
  },
  {
    label: '牙买加',
    label_en_us: 'Jamaica',
    label_zh_cn: '牙买加',
    value: 'JM',
    value_lower: 'jm',
  },
  {
    label: '英属维尔京群岛',
    label_en_us: 'British Virgin Islands',
    label_zh_cn: '英属维尔京群岛',
    value: 'VG',
    value_lower: 'vg',
  },
  {
    label: '阿根廷',
    label_en_us: 'Argentina',
    label_zh_cn: '阿根廷',
    value: 'AR',
    value_lower: 'ar',
  },
  {
    label: '巴拉圭',
    label_en_us: 'Paraguay',
    label_zh_cn: '巴拉圭',
    value: 'PY',
    value_lower: 'py',
  },
  {
    label: '巴西',
    label_en_us: 'Brazil',
    label_zh_cn: '巴西',
    value: 'BR',
    value_lower: 'br',
  },
  {
    label: '玻利维亚',
    label_en_us: 'Bolivia',
    label_zh_cn: '玻利维亚',
    value: 'BO',
    value_lower: 'bo',
  },
  {
    label: '厄瓜多尔',
    label_en_us: 'Ecuador',
    label_zh_cn: '厄瓜多尔',
    value: 'EC',
    value_lower: 'ec',
  },
  {
    label: '哥伦比亚',
    label_en_us: 'Columbia',
    label_zh_cn: '哥伦比亚',
    value: 'CO',
    value_lower: 'co',
  },
  {
    label: '圭亚那',
    label_en_us: 'Guyana',
    label_zh_cn: '圭亚那',
    value: 'GY',
    value_lower: 'gy',
  },
  {
    label: '秘鲁',
    label_en_us: 'Peru',
    label_zh_cn: '秘鲁',
    value: 'PE',
    value_lower: 'pe',
  },
  {
    label: '苏里南',
    label_en_us: 'Suriname',
    label_zh_cn: '苏里南',
    value: 'SR',
    value_lower: 'sr',
  },
  {
    label: '委内瑞拉',
    label_en_us: 'Venezuela',
    label_zh_cn: '委内瑞拉',
    value: 'VE',
    value_lower: 've',
  },
  {
    label: '乌拉圭',
    label_en_us: 'Uruguay',
    label_zh_cn: '乌拉圭',
    value: 'UY',
    value_lower: 'uy',
  },
  {
    label: '智利',
    label_en_us: 'Chile',
    label_zh_cn: '智利',
    value: 'CL',
    value_lower: 'cl',
  },
  {
    label: '阿尔巴尼亚',
    label_en_us: 'Albania',
    label_zh_cn: '阿尔巴尼亚',
    value: 'AL',
    value_lower: 'al',
  },
  {
    label: '爱尔兰',
    label_en_us: 'Ireland',
    label_zh_cn: '爱尔兰',
    value: 'IE',
    value_lower: 'ie',
  },
  {
    label: '爱沙尼亚',
    label_en_us: 'Estonia',
    label_zh_cn: '爱沙尼亚',
    value: 'EE',
    value_lower: 'ee',
  },
  {
    label: '奥地利',
    label_en_us: 'Austria',
    label_zh_cn: '奥地利',
    value: 'AT',
    value_lower: 'at',
  },
  {
    label: '白俄罗斯',
    label_en_us: 'Belarus',
    label_zh_cn: '白俄罗斯',
    value: 'BY',
    value_lower: 'by',
  },
  {
    label: '保加利亚',
    label_en_us: 'Bulgaria',
    label_zh_cn: '保加利亚',
    value: 'BG',
    value_lower: 'bg',
  },
  {
    label: '比利时',
    label_en_us: 'Belgium',
    label_zh_cn: '比利时',
    value: 'BE',
    value_lower: 'be',
  },
  {
    label: '冰岛',
    label_en_us: 'Iceland',
    label_zh_cn: '冰岛',
    value: 'IS',
    value_lower: 'is',
  },
  {
    label: '波兰',
    label_en_us: 'Poland',
    label_zh_cn: '波兰',
    value: 'PL',
    value_lower: 'pl',
  },
  {
    label: '丹麦',
    label_en_us: 'Denmark',
    label_zh_cn: '丹麦',
    value: 'DK',
    value_lower: 'dk',
  },
  {
    label: '德国',
    label_en_us: 'Germany',
    label_zh_cn: '德国',
    value: 'DE',
    value_lower: 'de',
  },
  {
    label: '俄罗斯',
    label_en_us: 'Russia',
    label_zh_cn: '俄罗斯',
    value: 'RU',
    value_lower: 'ru',
  },
  {
    label: '法国',
    label_en_us: 'France',
    label_zh_cn: '法国',
    value: 'FR',
    value_lower: 'fr',
  },
  {
    label: '芬兰',
    label_en_us: 'Finland',
    label_zh_cn: '芬兰',
    value: 'FI',
    value_lower: 'fi',
  },
  {
    label: '荷兰',
    label_en_us: 'Netherlands',
    label_zh_cn: '荷兰',
    value: 'NL',
    value_lower: 'nl',
  },
  {
    label: '捷克',
    label_en_us: 'Czech Republic',
    label_zh_cn: '捷克',
    value: 'CZ',
    value_lower: 'cz',
  },
  {
    label: '克罗地亚',
    label_en_us: 'Croatia',
    label_zh_cn: '克罗地亚',
    value: 'HR',
    value_lower: 'hr',
  },
  {
    label: '拉脱维亚',
    label_en_us: 'Latvia',
    label_zh_cn: '拉脱维亚',
    value: 'LV',
    value_lower: 'lv',
  },
  {
    label: '立陶宛',
    label_en_us: 'Lithuania',
    label_zh_cn: '立陶宛',
    value: 'LT',
    value_lower: 'lt',
  },
  {
    label: '卢森堡',
    label_en_us: 'Luxembourg',
    label_zh_cn: '卢森堡',
    value: 'LU',
    value_lower: 'lu',
  },
  {
    label: '罗马尼亚',
    label_en_us: 'Romania',
    label_zh_cn: '罗马尼亚',
    value: 'RO',
    value_lower: 'ro',
  },
  {
    label: '马其他',
    label_en_us: 'Ma Other',
    label_zh_cn: '马其他',
    value: 'MT',
    value_lower: 'mt',
  },
  {
    label: '马其顿（前南斯拉夫）',
    label_en_us: 'Macedonia (former Yugoslavia)',
    label_zh_cn: '马其顿（前南斯拉夫）',
    value: 'MK',
    value_lower: 'mk',
  },
  {
    label: '摩尔多瓦共和国',
    label_en_us: 'Republic of Moldova',
    label_zh_cn: '摩尔多瓦共和国',
    value: 'MD',
    value_lower: 'md',
  },
  {
    label: '挪威',
    label_en_us: 'Norway',
    label_zh_cn: '挪威',
    value: 'NO',
    value_lower: 'no',
  },
  {
    label: '葡萄牙',
    label_en_us: 'Portugal',
    label_zh_cn: '葡萄牙',
    value: 'PT',
    value_lower: 'pt',
  },
  {
    label: '瑞典',
    label_en_us: 'Sweden',
    label_zh_cn: '瑞典',
    value: 'SE',
    value_lower: 'se',
  },
  {
    label: '瑞士',
    label_en_us: 'Switzerland',
    label_zh_cn: '瑞士',
    value: 'CH',
    value_lower: 'ch',
  },
  {
    label: '斯洛伐克',
    label_en_us: 'Slovakia',
    label_zh_cn: '斯洛伐克',
    value: 'SK',
    value_lower: 'sk',
  },
  {
    label: '斯洛文尼亚',
    label_en_us: 'Slovenia',
    label_zh_cn: '斯洛文尼亚',
    value: 'SI',
    value_lower: 'si',
  },
  {
    label: '乌克兰',
    label_en_us: 'Ukraine',
    label_zh_cn: '乌克兰',
    value: 'UA',
    value_lower: 'ua',
  },
  {
    label: '希腊',
    label_en_us: 'Greece',
    label_zh_cn: '希腊',
    value: 'GR',
    value_lower: 'gr',
  },
  {
    label: '西班牙',
    label_en_us: 'Spain',
    label_zh_cn: '西班牙',
    value: 'ES',
    value_lower: 'es',
  },
  {
    label: '匈牙利',
    label_en_us: 'Hungary',
    label_zh_cn: '匈牙利',
    value: 'HU',
    value_lower: 'hu',
  },
  {
    label: '意大利',
    label_en_us: 'Italy',
    label_zh_cn: '意大利',
    value: 'IT',
    value_lower: 'it',
  },
  {
    label: '澳大利亚',
    label_en_us: 'Australia',
    label_zh_cn: '澳大利亚',
    value: 'AU',
    value_lower: 'au',
  },
  {
    label: '巴布亚新几内亚',
    label_en_us: 'Papua New Guinea',
    label_zh_cn: '巴布亚新几内亚',
    value: 'PG',
    value_lower: 'pg',
  },
  {
    label: '斐济',
    label_en_us: 'Fiji',
    label_zh_cn: '斐济',
    value: 'FJ',
    value_lower: 'fj',
  },
  {
    label: '密克罗尼西亚联邦',
    label_en_us: 'Federated States of Micronesia',
    label_zh_cn: '密克罗尼西亚联邦',
    value: 'FM',
    value_lower: 'fm',
  },
  {
    label: '帕劳',
    label_en_us: 'Palau',
    label_zh_cn: '帕劳',
    value: 'PW',
    value_lower: 'pw',
  },
  {
    label: '所罗门群岛',
    label_en_us: 'Solomon Islands',
    label_zh_cn: '所罗门群岛',
    value: 'SB',
    value_lower: 'sb',
  },
  {
    label: '新西兰',
    label_en_us: 'New Zealand',
    label_zh_cn: '新西兰',
    value: 'NZ',
    value_lower: 'nz',
  },
  {
    label: '塞浦路斯',
    label_en_us: 'Cyprus',
    label_zh_cn: '塞浦路斯',
    value: 'CY',
    value_lower: 'cy',
  },
  {
    label: '阿尔及利亚',
    label_en_us: 'Algeria',
    label_zh_cn: '阿尔及利亚',
    value: 'DZ',
    value_lower: 'dz',
  },
  {
    label: '埃及',
    label_en_us: 'Egypt',
    label_zh_cn: '埃及',
    value: 'EG',
    value_lower: 'eg',
  },
  {
    label: '安哥拉',
    label_en_us: 'Angola',
    label_zh_cn: '安哥拉',
    value: 'AO',
    value_lower: 'ao',
  },
  {
    label: '贝宁',
    label_en_us: 'Benin',
    label_zh_cn: '贝宁',
    value: 'BJ',
    value_lower: 'bj',
  },
  {
    label: '博茨瓦纳',
    label_en_us: 'Botswana',
    label_zh_cn: '博茨瓦纳',
    value: 'BW',
    value_lower: 'bw',
  },
  {
    label: '布基纳法索',
    label_en_us: 'Burkina Faso ',
    label_zh_cn: '布基纳法索',
    value: 'BF',
    value_lower: 'bf',
  },
  {
    label: '佛得角',
    label_en_us: 'Cape Verde',
    label_zh_cn: '佛得角',
    value: 'CV',
    value_lower: 'cv',
  },
  {
    label: '冈比亚',
    label_en_us: 'Gambia',
    label_zh_cn: '冈比亚',
    value: 'GM',
    value_lower: 'gm',
  },
  {
    label: '刚果共和国',
    label_en_us: 'Republic of Congo',
    label_zh_cn: '刚果共和国',
    value: 'CG',
    value_lower: 'cg',
  },
  {
    label: '几内亚比绍',
    label_en_us: 'Guinea-Bissau',
    label_zh_cn: '几内亚比绍',
    value: 'GW',
    value_lower: 'gw',
  },
  {
    label: '加纳',
    label_en_us: 'Ghana',
    label_zh_cn: '加纳',
    value: 'GH',
    value_lower: 'gh',
  },
  {
    label: '津巴布韦',
    label_en_us: 'Zimbabwe',
    label_zh_cn: '津巴布韦',
    value: 'ZW',
    value_lower: 'zw',
  },
  {
    label: '肯尼亚',
    label_en_us: 'Kenya',
    label_zh_cn: '肯尼亚',
    value: 'KE',
    value_lower: 'ke',
  },
  {
    label: '利比里亚',
    label_en_us: 'Liberia',
    label_zh_cn: '利比里亚',
    value: 'LR',
    value_lower: 'lr',
  },
  {
    label: '马达加斯加',
    label_en_us: 'Madagascar',
    label_zh_cn: '马达加斯加',
    value: 'MG',
    value_lower: 'mg',
  },
  {
    label: '马拉维',
    label_en_us: 'Malawi',
    label_zh_cn: '马拉维',
    value: 'MW',
    value_lower: 'mw',
  },
  {
    label: '马里',
    label_en_us: 'Mali',
    label_zh_cn: '马里',
    value: 'ML',
    value_lower: 'ml',
  },
  {
    label: '毛里求斯',
    label_en_us: 'Mauritius',
    label_zh_cn: '毛里求斯',
    value: 'MU',
    value_lower: 'mu',
  },
  {
    label: '毛里塔尼亚',
    label_en_us: 'Mauritania',
    label_zh_cn: '毛里塔尼亚',
    value: 'MR',
    value_lower: 'mr',
  },
  {
    label: '莫桑比克',
    label_en_us: 'Mozambique',
    label_zh_cn: '莫桑比克',
    value: 'MZ',
    value_lower: 'mz',
  },
  {
    label: '纳米比亚',
    label_en_us: 'Namibia',
    label_zh_cn: '纳米比亚',
    value: 'NA',
    value_lower: 'na',
  },
  {
    label: '南非',
    label_en_us: 'South Africa',
    label_zh_cn: '南非',
    value: 'ZA',
    value_lower: 'za',
  },
  {
    label: '尼日尔',
    label_en_us: 'Niger',
    label_zh_cn: '尼日尔',
    value: 'NE',
    value_lower: 'ne',
  },
  {
    label: '尼日利亚',
    label_en_us: 'Nigeria',
    label_zh_cn: '尼日利亚',
    value: 'NG',
    value_lower: 'ng',
  },
  {
    label: '塞内加尔',
    label_en_us: 'Senegal',
    label_zh_cn: '塞内加尔',
    value: 'SN',
    value_lower: 'sn',
  },
  {
    label: '塞舌尔',
    label_en_us: 'Seychelles',
    label_zh_cn: '塞舌尔',
    value: 'SC',
    value_lower: 'sc',
  },
  {
    label: '圣多美和普林西比',
    label_en_us: ' Sao Tome and Principe',
    label_zh_cn: '圣多美和普林西比',
    value: 'ST',
    value_lower: 'st',
  },
  {
    label: '斯威士兰',
    label_en_us: 'Eswatini',
    label_zh_cn: '斯威士兰',
    value: 'SZ',
    value_lower: 'sz',
  },
  {
    label: '坦桑尼亚联合共和国',
    label_en_us: 'United Republic of Tanzania',
    label_zh_cn: '坦桑尼亚联合共和国',
    value: 'TZ',
    value_lower: 'tz',
  },
  {
    label: '突尼斯',
    label_en_us: 'Tunisia',
    label_zh_cn: '突尼斯',
    value: 'TN',
    value_lower: 'tn',
  },
  {
    label: '乌干达',
    label_en_us: 'Uganda',
    label_zh_cn: '乌干达',
    value: 'UG',
    value_lower: 'ug',
  },
  {
    label: '乍得',
    label_en_us: 'Chad',
    label_zh_cn: '乍得',
    value: 'TD',
    value_lower: 'td',
  },
  {
    label: '塞拉利昂',
    label_en_us: 'Sierra Leone',
    label_zh_cn: '塞拉利昂',
    value: 'SL',
    value_lower: 'sl',
  },
];
