export default [
  {
    label: '阿尔及利亚',
    label_en_us: 'Algeria',
    label_zh_cn: '阿尔及利亚',
    value: 'DZ',
    value_lower: 'dz',
    lang: 'ar,en',
  },
  {
    label: '阿根廷',
    label_en_us: 'Argentina',
    label_zh_cn: '阿根廷',
    value: 'AR',
    value_lower: 'ar',
    lang: 'en,sp',
  },
  {
    label: '澳大利亚',
    label_en_us: 'Australia',
    label_zh_cn: '澳大利亚',
    value: 'AU',
    value_lower: 'au',
    lang: 'au',
  },
  {
    label: '奥地利',
    label_en_us: 'Austria',
    label_zh_cn: '奥地利',
    value: 'AT',
    value_lower: 'at',
    lang: 'de,en',
  },
  {
    label: '白俄罗斯',
    label_en_us: 'Belarus',
    label_zh_cn: '白俄罗斯',
    value: 'BY',
    value_lower: 'by',
    lang: 'en',
  },
  {
    label: '比利时',
    label_en_us: 'Belgium',
    label_zh_cn: '比利时',
    value: 'BE',
    value_lower: 'be',
    lang: 'en,fr,nl',
  },
  {
    label: '巴西',
    label_en_us: 'Brazil',
    label_zh_cn: '巴西',
    value: 'BR',
    value_lower: 'br',
    lang: 'br,en',
  },
  {
    label: '保加利亚',
    label_en_us: 'Bulgaria',
    label_zh_cn: '保加利亚',
    value: 'BG',
    value_lower: 'bg',
    lang: 'en',
  },
  {
    label: '加拿大',
    label_en_us: 'Canada',
    label_zh_cn: '加拿大',
    value: 'CA',
    value_lower: 'ca',
    lang: 'ca,qu',
  },
  {
    label: '智利',
    label_en_us: 'Chile',
    label_zh_cn: '智利',
    value: 'CL',
    value_lower: 'cl',
    lang: 'en,sp',
  },
  {
    label: '中国',
    label_en_us: 'China',
    label_zh_cn: '中国',
    value: 'CN',
    value_lower: 'cn',
    lang: 'cn,en',
  },
  {
    label: '哥伦比亚',
    label_en_us: 'Columbia',
    label_zh_cn: '哥伦比亚',
    value: 'CO',
    value_lower: 'co',
    lang: 'en,sp',
  },
  {
    label: '克罗地亚',
    label_en_us: 'Croatia',
    label_zh_cn: '克罗地亚',
    value: 'HR',
    value_lower: 'hr',
    lang: 'en,hr',
  },
  {
    label: '捷克',
    label_en_us: 'Czech Republic',
    label_zh_cn: '捷克',
    value: 'CZ',
    value_lower: 'cz',
    lang: 'cs,en',
  },
  {
    label: '丹麦',
    label_en_us: 'Denmark',
    label_zh_cn: '丹麦',
    value: 'DK',
    value_lower: 'dk',
    lang: 'da,en',
  },
  {
    label: '厄瓜多尔',
    label_en_us: 'Ecuador',
    label_zh_cn: '厄瓜多尔',
    value: 'EC',
    value_lower: 'ec',
    lang: 'en,sp',
  },
  {
    label: '埃及',
    label_en_us: 'Egypt',
    label_zh_cn: '埃及',
    value: 'EG',
    value_lower: 'eg',
    lang: 'ar,en',
  },
  {
    label: '爱沙尼亚',
    label_en_us: 'Estonia',
    label_zh_cn: '爱沙尼亚',
    value: 'EE',
    value_lower: 'ee',
    lang: 'en',
  },
  {
    label: '芬兰',
    label_en_us: 'Finland',
    label_zh_cn: '芬兰',
    value: 'FI',
    value_lower: 'fi',
    lang: 'en,fi',
  },
  {
    label: '法国',
    label_en_us: 'France',
    label_zh_cn: '法国',
    value: 'FR',
    value_lower: 'fr',
    lang: 'en,fr',
  },
  {
    label: '德国',
    label_en_us: 'Germany',
    label_zh_cn: '德国',
    value: 'DE',
    value_lower: 'de',
    lang: 'de,en',
  },
  {
    label: '希腊',
    label_en_us: 'Greece',
    label_zh_cn: '希腊',
    value: 'GR',
    value_lower: 'gr',
    lang: 'el,en',
  },
  {
    label: '香港',
    label_en_us: 'Hong Kong',
    label_zh_cn: '香港',
    value: 'HK',
    value_lower: 'hk',
    lang: 'en,zh',
  },
  {
    label: '匈牙利',
    label_en_us: 'Hungary',
    label_zh_cn: '匈牙利',
    value: 'HU',
    value_lower: 'hu',
    lang: 'en,hu',
  },
  {
    label: '冰岛',
    label_en_us: 'Iceland',
    label_zh_cn: '冰岛',
    value: 'IS',
    value_lower: 'is',
    lang: 'en',
  },
  {
    label: '印度',
    label_en_us: 'India',
    label_zh_cn: '印度',
    value: 'IN',
    value_lower: 'in',
    lang: 'en,hi',
  },
  {
    label: '印尼',
    label_en_us: 'Indonesia',
    label_zh_cn: '印尼',
    value: 'ID',
    value_lower: 'id',
    lang: 'en,id',
  },
  {
    label: '爱尔兰',
    label_en_us: 'Ireland',
    label_zh_cn: '爱尔兰',
    value: 'IE',
    value_lower: 'ie',
    lang: 'en',
  },
  {
    label: '以色列',
    label_en_us: 'Israel',
    label_zh_cn: '以色列',
    value: 'IL',
    value_lower: 'il',
    lang: 'en,he',
  },
  {
    label: '意大利',
    label_en_us: 'Italy',
    label_zh_cn: '意大利',
    value: 'IT',
    value_lower: 'it',
    lang: 'en,it',
  },
  {
    label: '日本',
    label_en_us: 'Japan',
    label_zh_cn: '日本',
    value: 'JP',
    value_lower: 'jp',
    lang: 'ja,us',
  },
  {
    label: '约旦',
    label_en_us: 'Jordan',
    label_zh_cn: '约旦',
    value: 'JO',
    value_lower: 'jo',
    lang: 'ar,en',
  },
  {
    label: '哈萨克斯坦',
    label_en_us: 'Kazakhstan',
    label_zh_cn: '哈萨克斯坦',
    value: 'KZ',
    value_lower: 'kz',
    lang: 'en',
  },
  {
    label: '韩国',
    label_en_us: 'Korea',
    label_zh_cn: '韩国',
    value: 'KR',
    value_lower: 'kr',
    lang: 'en,ko',
  },
  {
    label: '科威特',
    label_en_us: 'Kuwait',
    label_zh_cn: '科威特',
    value: 'KW',
    value_lower: 'kw',
    lang: 'ar,en',
  },
  {
    label: '拉脱维亚',
    label_en_us: 'Latvia',
    label_zh_cn: '拉脱维亚',
    value: 'LV',
    value_lower: 'lv',
    lang: 'en',
  },
  {
    label: '黎巴嫩',
    label_en_us: 'Lebanon',
    label_zh_cn: '黎巴嫩',
    value: 'LB',
    value_lower: 'lb',
    lang: 'ar,en',
  },
  {
    label: '立陶宛',
    label_en_us: 'Lithuania',
    label_zh_cn: '立陶宛',
    value: 'LT',
    value_lower: 'lt',
    lang: 'en',
  },
  {
    label: '卢森堡',
    label_en_us: 'Luxembourg',
    label_zh_cn: '卢森堡',
    value: 'LU',
    value_lower: 'lu',
    lang: 'de,en,fr',
  },
  {
    label: '澳门',
    label_en_us: 'Macao',
    label_zh_cn: '澳门',
    value: 'MO',
    value_lower: 'mo',
    lang: 'en,zh',
  },
  {
    label: '马来西亚',
    label_en_us: 'Malaysia',
    label_zh_cn: '马来西亚',
    value: 'MY',
    value_lower: 'my',
    lang: 'en,ms',
  },
  {
    label: '墨西哥',
    label_en_us: 'Mexico',
    label_zh_cn: '墨西哥',
    value: 'MX',
    value_lower: 'mx',
    lang: 'en,sp',
  },
  {
    label: '荷兰',
    label_en_us: 'Netherlands',
    label_zh_cn: '荷兰',
    value: 'NL',
    value_lower: 'nl',
    lang: 'en,nl',
  },
  {
    label: '新西兰',
    label_en_us: 'New Zealand',
    label_zh_cn: '新西兰',
    value: 'NZ',
    value_lower: 'nz',
    lang: 'au',
  },
  {
    label: '尼日利亚',
    label_en_us: 'Nigeria',
    label_zh_cn: '尼日利亚',
    value: 'NG',
    value_lower: 'ng',
    lang: 'en',
  },
  {
    label: '挪威',
    label_en_us: 'Norway',
    label_zh_cn: '挪威',
    value: 'NO',
    value_lower: 'no',
    lang: 'en,no',
  },
  {
    label: '阿曼',
    label_en_us: 'Oman',
    label_zh_cn: '阿曼',
    value: 'OM',
    value_lower: 'om',
    lang: 'ar,en',
  },
  {
    label: '巴基斯坦',
    label_en_us: 'Pakistan',
    label_zh_cn: '巴基斯坦',
    value: 'PK',
    value_lower: 'pk',
    lang: 'en',
  },
  {
    label: '秘鲁',
    label_en_us: 'Peru',
    label_zh_cn: '秘鲁',
    value: 'PE',
    value_lower: 'pe',
    lang: 'en,sp',
  },
  {
    label: '菲律宾',
    label_en_us: 'The Philippines',
    label_zh_cn: '菲律宾',
    value: 'PH',
    value_lower: 'ph',
    lang: 'en',
  },
  {
    label: '波兰',
    label_en_us: 'Poland',
    label_zh_cn: '波兰',
    value: 'PL',
    value_lower: 'pl',
    lang: 'en,pl',
  },
  {
    label: '葡萄牙',
    label_en_us: 'Portugal',
    label_zh_cn: '葡萄牙',
    value: 'PT',
    value_lower: 'pt',
    lang: 'en,pt',
  },
  {
    label: '卡塔尔',
    label_en_us: 'Qatar',
    label_zh_cn: '卡塔尔',
    value: 'QA',
    value_lower: 'qa',
    lang: 'ar,en',
  },
  {
    label: '罗马尼亚',
    label_en_us: 'Romania',
    label_zh_cn: '罗马尼亚',
    value: 'RO',
    value_lower: 'ro',
    lang: 'en,ro',
  },
  {
    label: '俄罗斯',
    label_en_us: 'Russia',
    label_zh_cn: '俄罗斯',
    value: 'RU',
    value_lower: 'ru',
    lang: 'en,ru',
  },
  {
    label: '沙特阿拉伯',
    label_en_us: 'Saudi Arabia',
    label_zh_cn: '沙特阿拉伯',
    value: 'SA',
    value_lower: 'sa',
    lang: 'ar,en',
  },
  {
    label: '新加坡',
    label_en_us: 'Singapore',
    label_zh_cn: '新加坡',
    value: 'SG',
    value_lower: 'sg',
    lang: 'cn,en',
  },
  {
    label: '斯洛伐克',
    label_en_us: 'Slovakia',
    label_zh_cn: '斯洛伐克',
    value: 'SK',
    value_lower: 'sk',
    lang: 'en,sk',
  },
  {
    label: '斯洛文尼亚',
    label_en_us: 'Slovenia',
    label_zh_cn: '斯洛文尼亚',
    value: 'SI',
    value_lower: 'si',
    lang: 'en',
  },
  {
    label: '南非',
    label_en_us: 'South Africa',
    label_zh_cn: '南非',
    value: 'ZA',
    value_lower: 'za',
    lang: 'en',
  },
  {
    label: '西班牙',
    label_en_us: 'Spain',
    label_zh_cn: '西班牙',
    value: 'ES',
    value_lower: 'es',
    lang: 'ct,en,es',
  },
  {
    label: '瑞典',
    label_en_us: 'Sweden',
    label_zh_cn: '瑞典',
    value: 'SE',
    value_lower: 'se',
    lang: 'en,sv',
  },
  {
    label: '瑞士',
    label_en_us: 'Switzerland',
    label_zh_cn: '瑞士',
    value: 'CH',
    value_lower: 'ch',
    lang: 'de,en,fr,it',
  },
  {
    label: '中国台湾省',
    label_en_us: 'Taiwan, China Province, China',
    label_zh_cn: '中国台湾省',
    value: 'TW',
    value_lower: 'tw',
    lang: 'en,zh',
  },
  {
    label: '泰国',
    label_en_us: 'Thailand',
    label_zh_cn: '泰国',
    value: 'TH',
    value_lower: 'th',
    lang: 'en,th',
  },
  {
    label: '突尼斯',
    label_en_us: 'Tunisia',
    label_zh_cn: '突尼斯',
    value: 'TN',
    value_lower: 'tn',
    lang: 'ar,en',
  },
  {
    label: '土耳其',
    label_en_us: 'Türkiye',
    label_zh_cn: '土耳其',
    value: 'TR',
    value_lower: 'tr',
    lang: 'en,tr',
  },
  {
    label: '乌克兰',
    label_en_us: 'Ukraine',
    label_zh_cn: '乌克兰',
    value: 'UA',
    value_lower: 'ua',
    lang: 'en,uk',
  },
  {
    label: '阿联酋',
    label_en_us: 'The United Arab Emirates',
    label_zh_cn: '阿联酋',
    value: 'AE',
    value_lower: 'ae',
    lang: 'ar,en',
  },
  {
    label: '英国',
    label_en_us: 'Britain',
    label_zh_cn: '英国',
    value: 'GB',
    value_lower: 'gb',
    lang: 'en',
  },
  {
    label: '美国',
    label_en_us: 'U.S.A',
    label_zh_cn: '美国',
    value: 'US',
    value_lower: 'us',
    lang: 'sp,us',
  },
  {
    label: '乌拉圭',
    label_en_us: 'Uruguay',
    label_zh_cn: '乌拉圭',
    value: 'UY',
    value_lower: 'uy',
    lang: 'en,sp',
  },
  {
    label: '委内瑞拉',
    label_en_us: 'Venezuela',
    label_zh_cn: '委内瑞拉',
    value: 'VE',
    value_lower: 've',
    lang: 'en,sp',
  },
  {
    label: '越南',
    label_en_us: 'Vietnam',
    label_zh_cn: '越南',
    value: 'VN',
    value_lower: 'vn',
    lang: 'en,vi',
  },
  {
    label: '津巴布韦',
    label_en_us: 'Zimbabwe',
    label_zh_cn: '津巴布韦',
    value: 'ZW',
    value_lower: 'zw',
    lang: 'en',
  },
];
