export default [
  {
    label: 'Asia',
    value: 'asia',
    sort: 10,
    label_en_us: 'Asia',
    label_zh_cn: '亚洲',
    children: [
      {
        label: 'China',
        value: 'CN',
        icon: 'area-cn',
        label_en_us: 'China',
        label_zh_cn: '中国',
        label_lower: 'china',
        value_lower: 'cn',
      },
      {
        label: 'Hong Kong',
        value: 'HK',
        icon: 'area-hk',
        label_en_us: 'Hong Kong',
        label_zh_cn: '中国香港',
        label_lower: 'hong kong',
        value_lower: 'hk',
      },
      {
        label: 'Taiwan',
        value: 'TW',
        icon: 'area-tw',
        label_en_us: 'Taiwan',
        label_zh_cn: '中国台湾',
        label_lower: 'taiwan',
        value_lower: 'tw',
      },
      {
        label: 'Japan',
        value: 'JP',
        icon: 'area-jp',
        label_en_us: 'Japan',
        label_zh_cn: '日本',
        label_lower: 'japan',
        value_lower: 'jp',
      },
      {
        label: 'Korea',
        value: 'KR',
        icon: 'area-kr',
        label_en_us: 'Korea',
        label_zh_cn: '韩国',
        label_lower: 'korea',
        value_lower: 'kr',
      },
      {
        label: 'Macao',
        value: 'MO',
        icon: 'area-mo',
        label_en_us: 'Macao',
        label_zh_cn: '中国澳门',
        label_lower: 'macao',
        value_lower: 'mo',
      },
      {
        label: 'Pakistan',
        value: 'PK',
        icon: 'area-pk',
        label_en_us: 'Pakistan',
        label_zh_cn: '巴基斯坦',
        label_lower: 'pakistan',
        value_lower: 'pk',
      },
      {
        label: 'Philippines',
        value: 'PH',
        icon: 'area-ph',
        label_en_us: 'Philippines',
        label_zh_cn: '菲律宾',
        label_lower: 'philippines',
        value_lower: 'ph',
      },
      {
        label: 'Kazakhstan',
        value: 'KZ',
        icon: 'area-kz',
        label_en_us: 'Kazakhstan',
        label_zh_cn: '哈萨克斯坦',
        label_lower: 'kazakhstan',
        value_lower: 'kz',
      },
      {
        label: 'Cambodia',
        value: 'KH',
        icon: 'area-kh',
        label_en_us: 'Cambodia',
        label_zh_cn: '柬埔寨',
        label_lower: 'cambodia',
        value_lower: 'kh',
      },
      {
        label: 'Malaysia',
        value: 'MY',
        icon: 'area-my',
        label_en_us: 'Malaysia',
        label_zh_cn: '马来西亚',
        label_lower: 'malaysia',
        value_lower: 'my',
      },
      {
        label: 'Thailand',
        value: 'TH',
        icon: 'area-th',
        label_en_us: 'Thailand',
        label_zh_cn: '泰国',
        label_lower: 'thailand',
        value_lower: 'th',
      },
      {
        label: 'Singapore',
        value: 'SG',
        icon: 'area-sg',
        label_en_us: 'Singapore',
        label_zh_cn: '新加坡',
        label_lower: 'singapore',
        value_lower: 'sg',
      },
      {
        label: 'Indonesia',
        value: 'ID',
        icon: 'area-id',
        label_en_us: 'Indonesia',
        label_zh_cn: '印度尼西亚',
        label_lower: 'indonesia',
        value_lower: 'id',
      },
      {
        label: 'Vietnam',
        value: 'VN',
        icon: 'area-vn',
        label_en_us: 'Vietnam',
        label_zh_cn: '越南',
        label_lower: 'vietnam',
        value_lower: 'vn',
      },
      {
        label: 'United Arab Emirates',
        value: 'AE',
        icon: 'area-ae',
        label_en_us: 'United Arab Emirates',
        label_zh_cn: '阿拉伯联合酋长国',
        label_lower: 'united arab emirates',
        value_lower: 'ae',
      },
      {
        label: 'Oman',
        value: 'OM',
        icon: 'area-om',
        label_en_us: 'Oman',
        label_zh_cn: '阿曼',
        label_lower: 'oman',
        value_lower: 'om',
      },
      {
        label: 'Azerbaijan',
        value: 'AZ',
        icon: 'area-az',
        label_en_us: 'Azerbaijan',
        label_zh_cn: '阿塞拜疆',
        label_lower: 'azerbaijan',
        value_lower: 'az',
      },
      {
        label: 'Qatar',
        value: 'QA',
        icon: 'area-qa',
        label_en_us: 'Qatar',
        label_zh_cn: '卡塔尔',
        label_lower: 'qatar',
        value_lower: 'qa',
      },
      {
        label: 'Kuwait',
        value: 'KW',
        icon: 'area-kw',
        label_en_us: 'Kuwait',
        label_zh_cn: '科威特',
        label_lower: 'kuwait',
        value_lower: 'kw',
      },
      {
        label: 'Lebanon',
        value: 'LB',
        icon: 'area-lb',
        label_en_us: 'Lebanon',
        label_zh_cn: '黎巴嫩',
        label_lower: 'lebanon',
        value_lower: 'lb',
      },
      {
        label: 'Saudi Arabia',
        value: 'SA',
        icon: 'area-sa',
        label_en_us: 'Saudi Arabia',
        label_zh_cn: '沙特阿拉伯',
        label_lower: 'saudi arabia',
        value_lower: 'sa',
      },
      {
        label: 'Israel',
        value: 'IL',
        icon: 'area-il',
        label_en_us: 'Israel',
        label_zh_cn: '以色列',
        label_lower: 'israel',
        value_lower: 'il',
      },
      {
        label: 'India',
        value: 'IN',
        icon: 'area-in',
        label_en_us: 'India',
        label_zh_cn: '印度',
        label_lower: 'india',
        value_lower: 'in',
      },
      {
        label: 'Jordan',
        value: 'JO',
        icon: 'area-jo',
        label_en_us: 'Jordan',
        label_zh_cn: '约旦',
        label_lower: 'jordan',
        value_lower: 'jo',
      },
    ],
  },
  {
    label: 'North America',
    value: 'north america',
    sort: 20,
    label_en_us: 'North America',
    label_zh_cn: '北美洲',
    children: [
      {
        label: 'United States',
        value: 'US',
        icon: 'area-us',
        label_en_us: 'United States',
        label_zh_cn: '美国',
        label_lower: 'united states',
        value_lower: 'us',
      },
      {
        label: 'Canada',
        value: 'CA',
        icon: 'area-ca',
        label_en_us: 'Canada',
        label_zh_cn: '加拿大',
        label_lower: 'canada',
        value_lower: 'ca',
      },
      {
        label: 'Mexico',
        value: 'MX',
        icon: 'area-mx',
        label_en_us: 'Mexico',
        label_zh_cn: '墨西哥',
        label_lower: 'mexico',
        value_lower: 'mx',
      },
    ],
  },
  {
    label: 'Europe',
    value: 'europe',
    sort: 30,
    label_en_us: 'Europe',
    label_zh_cn: '欧洲',
    children: [
      {
        label: 'Albania',
        value: 'AL',
        icon: 'area-al',
        label_en_us: 'Albania',
        label_zh_cn: '阿尔巴尼亚',
        label_lower: 'albania',
        value_lower: 'al',
      },
      {
        label: 'Ireland',
        value: 'IE',
        icon: 'area-ie',
        label_en_us: 'Ireland',
        label_zh_cn: '爱尔兰',
        label_lower: 'ireland',
        value_lower: 'ie',
      },
      {
        label: 'Austria',
        value: 'AT',
        icon: 'area-at',
        label_en_us: 'Austria',
        label_zh_cn: '奥地利',
        label_lower: 'austria',
        value_lower: 'at',
      },
      {
        label: 'Belgium',
        value: 'BE',
        icon: 'area-be',
        label_en_us: 'Belgium',
        label_zh_cn: '比利时',
        label_lower: 'belgium',
        value_lower: 'be',
      },
      {
        label: 'Poland',
        value: 'PL',
        icon: 'area-pl',
        label_en_us: 'Poland',
        label_zh_cn: '波兰',
        label_lower: 'poland',
        value_lower: 'pl',
      },
      {
        label: 'Denmark',
        value: 'DK',
        icon: 'area-dk',
        label_en_us: 'Denmark',
        label_zh_cn: '丹麦',
        label_lower: 'denmark',
        value_lower: 'dk',
      },
      {
        label: 'Germany',
        value: 'DE',
        icon: 'area-de',
        label_en_us: 'Germany',
        label_zh_cn: '德国',
        label_lower: 'germany',
        value_lower: 'de',
      },
      {
        label: 'Russian Federation',
        value: 'RU',
        icon: 'area-ru',
        label_en_us: 'Russian Federation',
        label_zh_cn: '俄罗斯',
        label_lower: 'russian federation',
        value_lower: 'ru',
      },
      {
        label: 'France',
        value: 'FR',
        icon: 'area-fr',
        label_en_us: 'France',
        label_zh_cn: '法国',
        label_lower: 'france',
        value_lower: 'fr',
      },
      {
        label: 'Finland',
        value: 'FI',
        icon: 'area-fi',
        label_en_us: 'Finland',
        label_zh_cn: '芬兰',
        label_lower: 'finland',
        value_lower: 'fi',
      },
      {
        label: 'Netherlands',
        value: 'NL',
        icon: 'area-nl',
        label_en_us: 'Netherlands',
        label_zh_cn: '荷兰',
        label_lower: 'netherlands',
        value_lower: 'nl',
      },
      {
        label: 'Czech',
        value: 'CZ',
        icon: 'area-cz',
        label_en_us: 'Czech',
        label_zh_cn: '捷克共和国',
        label_lower: 'czech',
        value_lower: 'cz',
      },
      {
        label: 'Croatia',
        value: 'HR',
        icon: 'area-hr',
        label_en_us: 'Croatia',
        label_zh_cn: '克罗地亚',
        label_lower: 'croatia',
        value_lower: 'hr',
      },
      {
        label: 'Romania',
        value: 'RO',
        icon: 'area-ro',
        label_en_us: 'Romania',
        label_zh_cn: '罗马尼亚',
        label_lower: 'romania',
        value_lower: 'ro',
      },
      {
        label: 'Norway',
        value: 'NO',
        icon: 'area-no',
        label_en_us: 'Norway',
        label_zh_cn: '挪威',
        label_lower: 'norway',
        value_lower: 'no',
      },
      {
        label: 'Portugal',
        value: 'PT',
        icon: 'area-pt',
        label_en_us: 'Portugal',
        label_zh_cn: '葡萄牙',
        label_lower: 'portugal',
        value_lower: 'pt',
      },
      {
        label: 'Sweden',
        value: 'SE',
        icon: 'area-se',
        label_en_us: 'Sweden',
        label_zh_cn: '瑞典',
        label_lower: 'sweden',
        value_lower: 'se',
      },
      {
        label: 'Switzerland',
        value: 'CH',
        icon: 'area-ch',
        label_en_us: 'Switzerland',
        label_zh_cn: '瑞士',
        label_lower: 'switzerland',
        value_lower: 'ch',
      },
      {
        label: 'Ukraine',
        value: 'UA',
        icon: 'area-ua',
        label_en_us: 'Ukraine',
        label_zh_cn: '乌克兰',
        label_lower: 'ukraine',
        value_lower: 'ua',
      },
      {
        label: 'Greece',
        value: 'GR',
        icon: 'area-gr',
        label_en_us: 'Greece',
        label_zh_cn: '希腊',
        label_lower: 'greece',
        value_lower: 'gr',
      },
      {
        label: 'Spain',
        value: 'ES',
        icon: 'area-es',
        label_en_us: 'Spain',
        label_zh_cn: '西班牙',
        label_lower: 'spain',
        value_lower: 'es',
      },
      {
        label: 'Hungary',
        value: 'HU',
        icon: 'area-hu',
        label_en_us: 'Hungary',
        label_zh_cn: '匈牙利',
        label_lower: 'hungary',
        value_lower: 'hu',
      },
      {
        label: 'Italy',
        value: 'IT',
        icon: 'area-it',
        label_en_us: 'Italy',
        label_zh_cn: '意大利',
        label_lower: 'italy',
        value_lower: 'it',
      },
      {
        label: 'United Kingdom',
        value: 'GB',
        icon: 'area-gb',
        label_en_us: 'United Kingdom',
        label_zh_cn: '英国',
        label_lower: 'united kingdom',
        value_lower: 'gb',
      },
    ],
  },
  {
    label: 'Oceania',
    value: 'oceania',
    sort: 50,
    label_en_us: 'Oceania',
    label_zh_cn: '大洋洲',
    children: [
      {
        label: 'Australia',
        value: 'AU',
        icon: 'area-au',
        label_en_us: 'Australia',
        label_zh_cn: '澳大利亚',
        label_lower: 'australia',
        value_lower: 'au',
      },
      {
        label: 'New Zealand',
        value: 'NZ',
        icon: 'area-nz',
        label_en_us: 'New Zealand',
        label_zh_cn: '新西兰',
        label_lower: 'new zealand',
        value_lower: 'nz',
      },
    ],
  },
  {
    label: 'Africa',
    value: 'africa',
    sort: 70,
    label_en_us: 'Africa',
    label_zh_cn: '非洲',
    children: [
      {
        label: 'Egypt',
        value: 'EG',
        icon: 'area-eg',
        label_en_us: 'Egypt',
        label_zh_cn: '埃及',
        label_lower: 'egypt',
        value_lower: 'eg',
      },
      {
        label: 'South Africa',
        value: 'ZA',
        icon: 'area-za',
        label_en_us: 'South Africa',
        label_zh_cn: '南非',
        label_lower: 'south africa',
        value_lower: 'za',
      },
    ],
  },
];
