export default [
  {
    label: '中国',
    label_en_us: 'China',
    label_zh_cn: '中国',
    value: 'CN',
    value_lower: 'cn',
  },
  {
    label: '香港',
    label_en_us: 'Hong Kong',
    label_zh_cn: '香港',
    value: 'HK',
    value_lower: 'hk',
  },
  {
    label: '中国台湾省',
    label_en_us: 'Taiwan, China Province, China',
    label_zh_cn: '中国台湾省',
    value: 'TW',
    value_lower: 'tw',
  },
  {
    label: '日本',
    label_en_us: 'Japan',
    label_zh_cn: '日本',
    value: 'JP',
    value_lower: 'jp',
  },
  {
    label: '韩国',
    label_en_us: 'Korea',
    label_zh_cn: '韩国',
    value: 'KR',
    value_lower: 'kr',
  },
  {
    label: '澳门',
    label_en_us: 'Macao',
    label_zh_cn: '澳门',
    value: 'MO',
    value_lower: 'mo',
  },
  {
    label: '巴基斯坦',
    label_en_us: 'Pakistan',
    label_zh_cn: '巴基斯坦',
    value: 'PK',
    value_lower: 'pk',
  },
  {
    label: '菲律宾',
    label_en_us: 'The Philippines',
    label_zh_cn: '菲律宾',
    value: 'PH',
    value_lower: 'ph',
  },
  {
    label: '哈萨克斯坦',
    label_en_us: 'Kazakhstan',
    label_zh_cn: '哈萨克斯坦',
    value: 'KZ',
    value_lower: 'kz',
  },
  {
    label: '柬埔寨',
    label_en_us: 'Cambodia',
    label_zh_cn: '柬埔寨',
    value: 'KH',
    value_lower: 'kh',
  },
  {
    label: '马来西亚',
    label_en_us: 'Malaysia',
    label_zh_cn: '马来西亚',
    value: 'MY',
    value_lower: 'my',
  },
  {
    label: '泰国',
    label_en_us: 'Thailand',
    label_zh_cn: '泰国',
    value: 'TH',
    value_lower: 'th',
  },
  {
    label: '新加坡',
    label_en_us: 'Singapore',
    label_zh_cn: '新加坡',
    value: 'SG',
    value_lower: 'sg',
  },
  {
    label: '印尼',
    label_en_us: 'Indonesia',
    label_zh_cn: '印尼',
    value: 'ID',
    value_lower: 'id',
  },
  {
    label: '越南',
    label_en_us: 'Vietnam',
    label_zh_cn: '越南',
    value: 'VN',
    value_lower: 'vn',
  },
  {
    label: '阿联酋',
    label_en_us: 'The United Arab Emirates',
    label_zh_cn: '阿联酋',
    value: 'AE',
    value_lower: 'ae',
  },
  {
    label: '阿曼',
    label_en_us: 'Oman',
    label_zh_cn: '阿曼',
    value: 'OM',
    value_lower: 'om',
  },
  {
    label: '阿塞拜疆',
    label_en_us: 'Azerbaijan',
    label_zh_cn: '阿塞拜疆',
    value: 'AZ',
    value_lower: 'az',
  },
  {
    label: '卡塔尔',
    label_en_us: 'Qatar',
    label_zh_cn: '卡塔尔',
    value: 'QA',
    value_lower: 'qa',
  },
  {
    label: '科威特',
    label_en_us: 'Kuwait',
    label_zh_cn: '科威特',
    value: 'KW',
    value_lower: 'kw',
  },
  {
    label: '黎巴嫩',
    label_en_us: 'Lebanon',
    label_zh_cn: '黎巴嫩',
    value: 'LB',
    value_lower: 'lb',
  },
  {
    label: '沙特阿拉伯',
    label_en_us: 'Saudi Arabia',
    label_zh_cn: '沙特阿拉伯',
    value: 'SA',
    value_lower: 'sa',
  },
  {
    label: '以色列',
    label_en_us: 'Israel',
    label_zh_cn: '以色列',
    value: 'IL',
    value_lower: 'il',
  },
  {
    label: '印度',
    label_en_us: 'India',
    label_zh_cn: '印度',
    value: 'IN',
    value_lower: 'in',
  },
  {
    label: '约旦',
    label_en_us: 'Jordan',
    label_zh_cn: '约旦',
    value: 'JO',
    value_lower: 'jo',
  },
  {
    label: '美国',
    label_en_us: 'U.S.A',
    label_zh_cn: '美国',
    value: 'US',
    value_lower: 'us',
  },
  {
    label: '加拿大',
    label_en_us: 'Canada',
    label_zh_cn: '加拿大',
    value: 'CA',
    value_lower: 'ca',
  },
  {
    label: '墨西哥',
    label_en_us: 'Mexico',
    label_zh_cn: '墨西哥',
    value: 'MX',
    value_lower: 'mx',
  },
  {
    label: '阿尔巴尼亚',
    label_en_us: 'Albania',
    label_zh_cn: '阿尔巴尼亚',
    value: 'AL',
    value_lower: 'al',
  },
  {
    label: '爱尔兰',
    label_en_us: 'Ireland',
    label_zh_cn: '爱尔兰',
    value: 'IE',
    value_lower: 'ie',
  },
  {
    label: '奥地利',
    label_en_us: 'Austria',
    label_zh_cn: '奥地利',
    value: 'AT',
    value_lower: 'at',
  },
  {
    label: '比利时',
    label_en_us: 'Belgium',
    label_zh_cn: '比利时',
    value: 'BE',
    value_lower: 'be',
  },
  {
    label: '波兰',
    label_en_us: 'Poland',
    label_zh_cn: '波兰',
    value: 'PL',
    value_lower: 'pl',
  },
  {
    label: '丹麦',
    label_en_us: 'Denmark',
    label_zh_cn: '丹麦',
    value: 'DK',
    value_lower: 'dk',
  },
  {
    label: '德国',
    label_en_us: 'Germany',
    label_zh_cn: '德国',
    value: 'DE',
    value_lower: 'de',
  },
  {
    label: '俄罗斯',
    label_en_us: 'Russia',
    label_zh_cn: '俄罗斯',
    value: 'RU',
    value_lower: 'ru',
  },
  {
    label: '法国',
    label_en_us: 'France',
    label_zh_cn: '法国',
    value: 'FR',
    value_lower: 'fr',
  },
  {
    label: '芬兰',
    label_en_us: 'Finland',
    label_zh_cn: '芬兰',
    value: 'FI',
    value_lower: 'fi',
  },
  {
    label: '荷兰',
    label_en_us: 'Netherlands',
    label_zh_cn: '荷兰',
    value: 'NL',
    value_lower: 'nl',
  },
  {
    label: '捷克',
    label_en_us: 'Czech Republic',
    label_zh_cn: '捷克',
    value: 'CZ',
    value_lower: 'cz',
  },
  {
    label: '克罗地亚',
    label_en_us: 'Croatia',
    label_zh_cn: '克罗地亚',
    value: 'HR',
    value_lower: 'hr',
  },
  {
    label: '罗马尼亚',
    label_en_us: 'Romania',
    label_zh_cn: '罗马尼亚',
    value: 'RO',
    value_lower: 'ro',
  },
  {
    label: '挪威',
    label_en_us: 'Norway',
    label_zh_cn: '挪威',
    value: 'NO',
    value_lower: 'no',
  },
  {
    label: '葡萄牙',
    label_en_us: 'Portugal',
    label_zh_cn: '葡萄牙',
    value: 'PT',
    value_lower: 'pt',
  },
  {
    label: '瑞典',
    label_en_us: 'Sweden',
    label_zh_cn: '瑞典',
    value: 'SE',
    value_lower: 'se',
  },
  {
    label: '瑞士',
    label_en_us: 'Switzerland',
    label_zh_cn: '瑞士',
    value: 'CH',
    value_lower: 'ch',
  },
  {
    label: '乌克兰',
    label_en_us: 'Ukraine',
    label_zh_cn: '乌克兰',
    value: 'UA',
    value_lower: 'ua',
  },
  {
    label: '希腊',
    label_en_us: 'Greece',
    label_zh_cn: '希腊',
    value: 'GR',
    value_lower: 'gr',
  },
  {
    label: '西班牙',
    label_en_us: 'Spain',
    label_zh_cn: '西班牙',
    value: 'ES',
    value_lower: 'es',
  },
  {
    label: '匈牙利',
    label_en_us: 'Hungary',
    label_zh_cn: '匈牙利',
    value: 'HU',
    value_lower: 'hu',
  },
  {
    label: '意大利',
    label_en_us: 'Italy',
    label_zh_cn: '意大利',
    value: 'IT',
    value_lower: 'it',
  },
  {
    label: '英国',
    label_en_us: 'Britain',
    label_zh_cn: '英国',
    value: 'GB',
    value_lower: 'gb',
  },
  {
    label: '澳大利亚',
    label_en_us: 'Australia',
    label_zh_cn: '澳大利亚',
    value: 'AU',
    value_lower: 'au',
  },
  {
    label: '新西兰',
    label_en_us: 'New Zealand',
    label_zh_cn: '新西兰',
    value: 'NZ',
    value_lower: 'nz',
  },
  {
    label: '埃及',
    label_en_us: 'Egypt',
    label_zh_cn: '埃及',
    value: 'EG',
    value_lower: 'eg',
  },
  {
    label: '南非',
    label_en_us: 'South Africa',
    label_zh_cn: '南非',
    value: 'ZA',
    value_lower: 'za',
  },
];
