export default [
  {
    label_zh_cn: 'Etc/GMT+12',
    label_en_us: 'Etc/GMT+12',
    label: 'Etc/GMT+12',
    value: -12,
  },
  {
    label_zh_cn: 'Etc/GMT+11',
    label_en_us: 'Etc/GMT+11',
    label: 'Etc/GMT+11',
    value: -11,
  },
  {
    label_zh_cn: '太平洋/檀香山',
    label_en_us: 'Pacific/Honolulu',
    label: 'Pacific/Honolulu',
    value: -10,
  },
  {
    label_zh_cn: '美国/安克雷奇',
    label_en_us: 'America/Anchorage',
    label: 'America/Anchorage',
    value: -9,
  },
  {
    label_zh_cn: '美国/圣伊莎贝尔',
    label_en_us: 'America/Santa_Isabel',
    label: 'America/Santa_Isabel',
    value: -8,
  },
  {
    label_zh_cn: '美国/洛杉矶',
    label_en_us: 'America/Los_Angeles',
    label: 'America/Los_Angeles',
    value: -8,
  },
  {
    label_zh_cn: '美国/墨西哥',
    label_en_us: 'America/Chihuahua',
    label: 'America/Chihuahua',
    value: -7,
  },
  {
    label_zh_cn: '美国/凤凰城',
    label_en_us: 'America/Phoenix',
    label: 'America/Phoenix',
    value: -7,
  },
  {
    label_zh_cn: '美国/科罗拉多州',
    label_en_us: 'America/Denver',
    label: 'America/Denver',
    value: -7,
  },
  {
    label_zh_cn: '美国/危地马拉城',
    label_en_us: 'America/Guatemala',
    label: 'America/Guatemala',
    value: -6,
  },
  {
    label_zh_cn: '美国/芝加哥',
    label_en_us: 'America/Chicago',
    label: 'America/Chicago',
    value: -6,
  },
  {
    label_zh_cn: '美国/',
    label_en_us: 'America/Regina',
    label: 'America/Regina',
    value: -6,
  },
  {
    label_zh_cn: '美国/',
    label_en_us: 'America/Mexico_City',
    label: 'America/Mexico_City',
    value: -5,
  },
  {
    label_zh_cn: '美国/',
    label_en_us: 'America/Bogota',
    label: 'America/Bogota',
    value: -5,
  },
  {
    label_zh_cn: '美国/',
    label_en_us: 'America/Indiana/Indianapolis',
    label: 'America/Indiana/Indianapolis',
    value: -5,
  },
  {
    label_zh_cn: '美国/',
    label_en_us: 'America/New_York',
    label: 'America/New_York',
    value: -4,
  },
  {
    label_zh_cn: '美国/',
    label_en_us: 'America/Caracas',
    label: 'America/Caracas',
    value: -4,
  },
  {
    label_zh_cn: '美国/',
    label_en_us: 'America/Halifax',
    label: 'America/Halifax',
    value: -4,
  },
  {
    label_zh_cn: '美国/',
    label_en_us: 'America/Asuncion',
    label: 'America/Asuncion',
    value: -4,
  },
  {
    label_zh_cn: '美国/',
    label_en_us: 'America/La_Paz',
    label: 'America/La_Paz',
    value: -4,
  },
  {
    label_zh_cn: '美国/',
    label_en_us: 'America/Cuiaba',
    label: 'America/Cuiaba',
    value: -4,
  },
  {
    label_zh_cn: '美国/',
    label_en_us: 'America/Santiago',
    label: 'America/Santiago',
    value: -4,
  },
  {
    label_zh_cn: '美国/',
    label_en_us: 'America/St_Johns',
    label: 'America/St_Johns',
    value: -3,
  },
  {
    label_zh_cn: '美国/',
    label_en_us: 'America/Sao_Paulo',
    label: 'America/Sao_Paulo',
    value: -3,
  },
  {
    label_zh_cn: '美国/',
    label_en_us: 'America/Godthab',
    label: 'America/Godthab',
    value: -3,
  },
  {
    label_zh_cn: '美国/',
    label_en_us: 'America/Cayenne',
    label: 'America/Cayenne',
    value: -3,
  },
  {
    label_zh_cn: '美国/',
    label_en_us: 'America/Argentina/Buenos_Aires',
    label: 'America/Argentina/Buenos_Aires',
    value: -3,
  },
  {
    label_zh_cn: '美国/',
    label_en_us: 'America/Montevideo',
    label: 'America/Montevideo',
    value: -3,
  },
  {
    label_zh_cn: 'Etc/GMT+2',
    label_en_us: 'Etc/GMT+2',
    label: 'Etc/GMT+2',
    value: -2,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Atlantic/Cape_Verde',
    label: 'Atlantic/Cape_Verde',
    value: -1,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Atlantic/Azores',
    label: 'Atlantic/Azores',
    value: -1,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Africa/Casablanca',
    label: 'Africa/Casablanca',
    value: 0,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Atlantic/Reykjavik',
    label: 'Atlantic/Reykjavik',
    value: 0,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Europe/London',
    label: 'Europe/London',
    value: 0,
  },
  {
    label_zh_cn: 'Etc/GMT',
    label_en_us: 'Etc/GMT',
    label: 'Etc/GMT',
    value: 0,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Europe/Berlin',
    label: 'Europe/Berlin',
    value: 1,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Europe/Paris',
    label: 'Europe/Paris',
    value: 1,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Africa/Lagos',
    label: 'Africa/Lagos',
    value: 1,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Europe/Budapest',
    label: 'Europe/Budapest',
    value: 1,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Europe/Warsaw',
    label: 'Europe/Warsaw',
    value: 1,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Africa/Windhoek',
    label: 'Africa/Windhoek',
    value: 1,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Europe/Istanbul',
    label: 'Europe/Istanbul',
    value: 2,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Europe/Kiev',
    label: 'Europe/Kiev',
    value: 2,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Africa/Cairo',
    label: 'Africa/Cairo',
    value: 2,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Damascus',
    label: 'Asia/Damascus',
    value: 2,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Amman',
    label: 'Asia/Amman',
    value: 2,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Africa/Johannesburg',
    label: 'Africa/Johannesburg',
    value: 2,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Jerusalem',
    label: 'Asia/Jerusalem',
    value: 2,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Beirut',
    label: 'Asia/Beirut',
    value: 2,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Baghdad',
    label: 'Asia/Baghdad',
    value: 3,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Europe/Minsk',
    label: 'Europe/Minsk',
    value: 3,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Riyadh',
    label: 'Asia/Riyadh',
    value: 3,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Africa/Nairobi',
    label: 'Africa/Nairobi',
    value: 3,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Tehran',
    label: 'Asia/Tehran',
    value: 3,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Europe/Moscow',
    label: 'Europe/Moscow',
    value: 4,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Tbilisi',
    label: 'Asia/Tbilisi',
    value: 4,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Yerevan',
    label: 'Asia/Yerevan',
    value: 4,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Dubai',
    label: 'Asia/Dubai',
    value: 4,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Baku',
    label: 'Asia/Baku',
    value: 4,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Indian/Mauritius',
    label: 'Indian/Mauritius',
    value: 4,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Kabul',
    label: 'Asia/Kabul',
    value: 4,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Tashkent',
    label: 'Asia/Tashkent',
    value: 5,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Karachi',
    label: 'Asia/Karachi',
    value: 5,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Colombo',
    label: 'Asia/Colombo',
    value: 5,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Kolkata',
    label: 'Asia/Kolkata',
    value: 5,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Kathmandu',
    label: 'Asia/Kathmandu',
    value: 5,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Almaty',
    label: 'Asia/Almaty',
    value: 6,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Dhaka',
    label: 'Asia/Dhaka',
    value: 6,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Yekaterinburg',
    label: 'Asia/Yekaterinburg',
    value: 6,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Yangon',
    label: 'Asia/Yangon',
    value: 6,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Bangkok',
    label: 'Asia/Bangkok',
    value: 7,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Novosibirsk',
    label: 'Asia/Novosibirsk',
    value: 7,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Jakarta',
    label: 'Asia/Jakarta',
    value: 7,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Ho_Chi_Minh',
    label: 'Asia/Ho_Chi_Minh',
    value: 7,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Krasnoyarsk',
    label: 'Asia/Krasnoyarsk',
    value: 8,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Ulaanbaatar',
    label: 'Asia/Ulaanbaatar',
    value: 8,
  },
  {
    label_zh_cn: '亚洲/上海',
    label_en_us: 'Asia/Shanghai',
    label: 'Asia/Shanghai',
    value: 8,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Hong_Kong',
    label: 'Asia/Hong_Kong',
    value: 8,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Australia/Perth',
    label: 'Australia/Perth',
    value: 8,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Singapore',
    label: 'Asia/Singapore',
    value: 8,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Taipei',
    label: 'Asia/Taipei',
    value: 8,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Irkutsk',
    label: 'Asia/Irkutsk',
    value: 9,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Seoul',
    label: 'Asia/Seoul',
    value: 9,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Tokyo',
    label: 'Asia/Tokyo',
    value: 9,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Tokyo',
    label: 'Asia/Tokyo',
    value: 9,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Australia/Adelaide',
    label: 'Australia/Adelaide',
    value: 9,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Australia/Hobart',
    label: 'Australia/Hobart',
    value: 10,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Yakutsk',
    label: 'Asia/Yakutsk',
    value: 10,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Australia/Brisbane',
    label: 'Australia/Brisbane',
    value: 10,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Pacific/Port_Moresby',
    label: 'Pacific/Port_Moresby',
    value: 10,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Australia/Sydney',
    label: 'Australia/Sydney',
    value: 10,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Vladivostok',
    label: 'Asia/Vladivostok',
    value: 11,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Pacific/Guadalcanal',
    label: 'Pacific/Guadalcanal',
    value: 11,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Etc/GMT-12',
    label: 'Etc/GMT-12',
    value: 12,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Pacific/Fiji',
    label: 'Pacific/Fiji',
    value: 12,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Asia/Magadan',
    label: 'Asia/Magadan',
    value: 12,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Pacific/Auckland',
    label: 'Pacific/Auckland',
    value: 12,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Pacific/Tongatapu',
    label: 'Pacific/Tongatapu',
    value: 13,
  },
  {
    label_zh_cn: '',
    label_en_us: 'Pacific/Apia',
    label: 'Pacific/Apia',
    value: 13,
  },
];
