export default [
  {
    label: 'All',
    label_en_us: 'All',
    label_zh_cn: '全部',
    value: 36,
  },
  {
    label: 'App',
    label_en_us: 'App',
    label_zh_cn: '应用',
    value: 5000,
    children: [
      {
        label: 'All',
        label_en_us: 'All',
        label_zh_cn: '全部',
        value: 5000,
      },
      {
        label: 'Business',
        label_en_us: 'Business',
        label_zh_cn: '商务',
        value: 6000,
      },
      {
        label: 'Weather',
        label_en_us: 'Weather',
        label_zh_cn: '天气',
        value: 6001,
      },
      {
        label: 'Tools',
        label_en_us: 'Tools',
        label_zh_cn: '工具',
        value: 6002,
      },
      {
        label: 'Tourism',
        label_en_us: 'Tourism',
        label_zh_cn: '旅游',
        value: 6003,
      },
      {
        label: 'Sports',
        label_en_us: 'Sports',
        label_zh_cn: '体育',
        value: 6004,
      },
      {
        label: 'Social',
        label_en_us: 'Social',
        label_zh_cn: '社交',
        value: 6005,
      },
      {
        label: 'Reference',
        label_en_us: 'Reference',
        label_zh_cn: '参考',
        value: 6006,
      },
      {
        label: 'Efficiency',
        label_en_us: 'Efficiency',
        label_zh_cn: '效率',
        value: 6007,
      },
      {
        label: 'Photography and video',
        label_en_us: 'Photography and video',
        label_zh_cn: '摄影与录像',
        value: 6008,
      },
      {
        label: 'News',
        label_en_us: 'News',
        label_zh_cn: '新闻',
        value: 6009,
      },
      {
        label: 'Navigation',
        label_en_us: 'Navigation',
        label_zh_cn: '导航',
        value: 6010,
      },
      {
        label: 'Music',
        label_en_us: 'Music',
        label_zh_cn: '音乐',
        value: 6011,
      },
      {
        label: 'Life',
        label_en_us: 'Life',
        label_zh_cn: '生活',
        value: 6012,
      },
      {
        label: 'Health and fitness',
        label_en_us: 'Health and fitness',
        label_zh_cn: '健康健美',
        value: 6013,
      },
      {
        label: 'Finance',
        label_en_us: 'Finance',
        label_zh_cn: '财务',
        value: 6015,
      },
      {
        label: 'Entertainment',
        label_en_us: 'Entertainment',
        label_zh_cn: '娱乐',
        value: 6016,
      },
      {
        label: 'Education',
        label_en_us: 'Education',
        label_zh_cn: '教育',
        value: 6017,
      },
      {
        label: 'Books',
        label_en_us: 'Books',
        label_zh_cn: '图书',
        value: 6018,
      },
      {
        label: 'Medical care',
        label_en_us: 'Medical care',
        label_zh_cn: '医疗',
        value: 6020,
      },
      {
        label: 'Newspapers and magazines',
        label_en_us: 'Newspapers and magazines',
        label_zh_cn: '报刊杂志',
        value: 6021,
      },
      {
        label: 'Food and drink',
        label_en_us: 'Food and drink',
        label_zh_cn: '美食佳饮',
        value: 6023,
      },
      {
        label: 'Shopping',
        label_en_us: 'Shopping',
        label_zh_cn: '购物',
        value: 6024,
      },
      {
        label: 'Software development tools',
        label_en_us: 'Software development tools',
        label_zh_cn: '软件开发工具',
        value: 6026,
      },
      {
        label: 'Graphics and design',
        label_en_us: 'Graphics and design',
        label_zh_cn: '图形和设计',
        value: 6027,
      },
      {
        label: 'Children',
        label_en_us: 'Children',
        label_zh_cn: '儿童',
        value: 6061,
      },
    ],
  },
  {
    label: 'Game',
    label_en_us: 'Game',
    label_zh_cn: '游戏',
    value: 7000,
    children: [
      {
        label: 'All',
        label_en_us: 'All',
        label_zh_cn: '全部',
        value: 7000,
      },
      {
        label: 'Action',
        label_en_us: 'Action',
        label_zh_cn: '动作',
        value: 7001,
      },
      {
        label: 'Adventure',
        label_en_us: 'Adventure',
        label_zh_cn: '冒险',
        value: 7002,
      },
      {
        label: 'Leisure',
        label_en_us: 'Leisure',
        label_zh_cn: '休闲',
        value: 7003,
      },
      {
        label: 'Desktop',
        label_en_us: 'Desktop',
        label_zh_cn: '桌面',
        value: 7004,
      },
      {
        label: 'Card',
        label_en_us: 'Card',
        label_zh_cn: '卡牌',
        value: 7005,
      },
      {
        label: 'Casino game',
        label_en_us: 'Casino game',
        label_zh_cn: '娱乐场游戏',
        value: 7006,
      },
      {
        label: 'Family gathering',
        label_en_us: 'Family gathering',
        label_zh_cn: '家庭聚会',
        value: 7009,
      },
      {
        label: 'Music',
        label_en_us: 'Music',
        label_zh_cn: '音乐',
        value: 7011,
      },
      {
        label: 'Puzzle solving',
        label_en_us: 'Puzzle solving',
        label_zh_cn: '益智解谜',
        value: 7012,
      },
      {
        label: 'Race',
        label_en_us: 'Race',
        label_zh_cn: '竞速',
        value: 7013,
      },
      {
        label: 'Role playing',
        label_en_us: 'Role playing',
        label_zh_cn: '角色扮演',
        value: 7014,
      },
      {
        label: 'Simulation',
        label_en_us: 'Simulation',
        label_zh_cn: '模拟',
        value: 7015,
      },
      {
        label: 'Sports',
        label_en_us: 'Sports',
        label_zh_cn: '体育',
        value: 7016,
      },
      {
        label: 'Strategy',
        label_en_us: 'Strategy',
        label_zh_cn: '策略',
        value: 7017,
      },
      {
        label: 'Question and answer',
        label_en_us: 'Question and answer',
        label_zh_cn: '问答',
        value: 7018,
      },
      {
        label: 'Crossword puzzle',
        label_en_us: 'Crossword puzzle',
        label_zh_cn: '字谜',
        value: 7019,
      },
    ],
  },
];
